// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pm/pm.proto

package ipm

import (
	igm "api/igm"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	status "status"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PlayerCreateRequest struct {
	Pid                  string   `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password"`
	Port                 int64    `protobuf:"varint,4,opt,name=port,proto3" json:"port"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerCreateRequest) Reset()         { *m = PlayerCreateRequest{} }
func (m *PlayerCreateRequest) String() string { return proto.CompactTextString(m) }
func (*PlayerCreateRequest) ProtoMessage()    {}
func (*PlayerCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{0}
}
func (m *PlayerCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerCreateRequest.Unmarshal(m, b)
}
func (m *PlayerCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerCreateRequest.Marshal(b, m, deterministic)
}
func (m *PlayerCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerCreateRequest.Merge(m, src)
}
func (m *PlayerCreateRequest) XXX_Size() int {
	return xxx_messageInfo_PlayerCreateRequest.Size(m)
}
func (m *PlayerCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerCreateRequest proto.InternalMessageInfo

func (m *PlayerCreateRequest) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *PlayerCreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlayerCreateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *PlayerCreateRequest) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

type PlayerCreateResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status"`
	Pid                  string         `protobuf:"bytes,2,opt,name=pid,proto3" json:"pid"`
	Name                 string         `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	Password             string         `protobuf:"bytes,4,opt,name=password,proto3" json:"password"`
	Port                 int64          `protobuf:"varint,5,opt,name=port,proto3" json:"port"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PlayerCreateResponse) Reset()         { *m = PlayerCreateResponse{} }
func (m *PlayerCreateResponse) String() string { return proto.CompactTextString(m) }
func (*PlayerCreateResponse) ProtoMessage()    {}
func (*PlayerCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{1}
}
func (m *PlayerCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerCreateResponse.Unmarshal(m, b)
}
func (m *PlayerCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerCreateResponse.Marshal(b, m, deterministic)
}
func (m *PlayerCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerCreateResponse.Merge(m, src)
}
func (m *PlayerCreateResponse) XXX_Size() int {
	return xxx_messageInfo_PlayerCreateResponse.Size(m)
}
func (m *PlayerCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerCreateResponse proto.InternalMessageInfo

func (m *PlayerCreateResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *PlayerCreateResponse) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *PlayerCreateResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlayerCreateResponse) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *PlayerCreateResponse) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

type PlayerDeleteRequest struct {
	Pid                  string   `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerDeleteRequest) Reset()         { *m = PlayerDeleteRequest{} }
func (m *PlayerDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*PlayerDeleteRequest) ProtoMessage()    {}
func (*PlayerDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{2}
}
func (m *PlayerDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerDeleteRequest.Unmarshal(m, b)
}
func (m *PlayerDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerDeleteRequest.Marshal(b, m, deterministic)
}
func (m *PlayerDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerDeleteRequest.Merge(m, src)
}
func (m *PlayerDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_PlayerDeleteRequest.Size(m)
}
func (m *PlayerDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerDeleteRequest proto.InternalMessageInfo

func (m *PlayerDeleteRequest) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

type PlayerListRequest struct {
	Pid                  string   `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerListRequest) Reset()         { *m = PlayerListRequest{} }
func (m *PlayerListRequest) String() string { return proto.CompactTextString(m) }
func (*PlayerListRequest) ProtoMessage()    {}
func (*PlayerListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{3}
}
func (m *PlayerListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerListRequest.Unmarshal(m, b)
}
func (m *PlayerListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerListRequest.Marshal(b, m, deterministic)
}
func (m *PlayerListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerListRequest.Merge(m, src)
}
func (m *PlayerListRequest) XXX_Size() int {
	return xxx_messageInfo_PlayerListRequest.Size(m)
}
func (m *PlayerListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerListRequest proto.InternalMessageInfo

func (m *PlayerListRequest) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

type PlayerListResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status"`
	Players              []*PlayerInfo  `protobuf:"bytes,2,rep,name=players,proto3" json:"players"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PlayerListResponse) Reset()         { *m = PlayerListResponse{} }
func (m *PlayerListResponse) String() string { return proto.CompactTextString(m) }
func (*PlayerListResponse) ProtoMessage()    {}
func (*PlayerListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{4}
}
func (m *PlayerListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerListResponse.Unmarshal(m, b)
}
func (m *PlayerListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerListResponse.Marshal(b, m, deterministic)
}
func (m *PlayerListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerListResponse.Merge(m, src)
}
func (m *PlayerListResponse) XXX_Size() int {
	return xxx_messageInfo_PlayerListResponse.Size(m)
}
func (m *PlayerListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerListResponse proto.InternalMessageInfo

func (m *PlayerListResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *PlayerListResponse) GetPlayers() []*PlayerInfo {
	if m != nil {
		return m.Players
	}
	return nil
}

type PlayerInfo struct {
	Pid                  string   `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password"`
	Port                 int64    `protobuf:"varint,4,opt,name=port,proto3" json:"port"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{5}
}
func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(m, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *PlayerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlayerInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *PlayerInfo) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

type PlayerStartRequest struct {
	Pid                  string   `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerStartRequest) Reset()         { *m = PlayerStartRequest{} }
func (m *PlayerStartRequest) String() string { return proto.CompactTextString(m) }
func (*PlayerStartRequest) ProtoMessage()    {}
func (*PlayerStartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{6}
}
func (m *PlayerStartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerStartRequest.Unmarshal(m, b)
}
func (m *PlayerStartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerStartRequest.Marshal(b, m, deterministic)
}
func (m *PlayerStartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerStartRequest.Merge(m, src)
}
func (m *PlayerStartRequest) XXX_Size() int {
	return xxx_messageInfo_PlayerStartRequest.Size(m)
}
func (m *PlayerStartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerStartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerStartRequest proto.InternalMessageInfo

func (m *PlayerStartRequest) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

type PlayerStartResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PlayerStartResponse) Reset()         { *m = PlayerStartResponse{} }
func (m *PlayerStartResponse) String() string { return proto.CompactTextString(m) }
func (*PlayerStartResponse) ProtoMessage()    {}
func (*PlayerStartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{7}
}
func (m *PlayerStartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerStartResponse.Unmarshal(m, b)
}
func (m *PlayerStartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerStartResponse.Marshal(b, m, deterministic)
}
func (m *PlayerStartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerStartResponse.Merge(m, src)
}
func (m *PlayerStartResponse) XXX_Size() int {
	return xxx_messageInfo_PlayerStartResponse.Size(m)
}
func (m *PlayerStartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerStartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerStartResponse proto.InternalMessageInfo

func (m *PlayerStartResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type PlayerStopRequest struct {
	Pid                  string   `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerStopRequest) Reset()         { *m = PlayerStopRequest{} }
func (m *PlayerStopRequest) String() string { return proto.CompactTextString(m) }
func (*PlayerStopRequest) ProtoMessage()    {}
func (*PlayerStopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{8}
}
func (m *PlayerStopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerStopRequest.Unmarshal(m, b)
}
func (m *PlayerStopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerStopRequest.Marshal(b, m, deterministic)
}
func (m *PlayerStopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerStopRequest.Merge(m, src)
}
func (m *PlayerStopRequest) XXX_Size() int {
	return xxx_messageInfo_PlayerStopRequest.Size(m)
}
func (m *PlayerStopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerStopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerStopRequest proto.InternalMessageInfo

func (m *PlayerStopRequest) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

type SignInRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{9}
}
func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (m *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(m, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

func (m *SignInRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SignInRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignInResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status"`
	Etag                 string         `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SignInResponse) Reset()         { *m = SignInResponse{} }
func (m *SignInResponse) String() string { return proto.CompactTextString(m) }
func (*SignInResponse) ProtoMessage()    {}
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{10}
}
func (m *SignInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInResponse.Unmarshal(m, b)
}
func (m *SignInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInResponse.Marshal(b, m, deterministic)
}
func (m *SignInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInResponse.Merge(m, src)
}
func (m *SignInResponse) XXX_Size() int {
	return xxx_messageInfo_SignInResponse.Size(m)
}
func (m *SignInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignInResponse proto.InternalMessageInfo

func (m *SignInResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SignInResponse) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

type SignOutRequest struct {
	Etag                 string   `protobuf:"bytes,1,opt,name=etag,proto3" json:"etag"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignOutRequest) Reset()         { *m = SignOutRequest{} }
func (m *SignOutRequest) String() string { return proto.CompactTextString(m) }
func (*SignOutRequest) ProtoMessage()    {}
func (*SignOutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{11}
}
func (m *SignOutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignOutRequest.Unmarshal(m, b)
}
func (m *SignOutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignOutRequest.Marshal(b, m, deterministic)
}
func (m *SignOutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignOutRequest.Merge(m, src)
}
func (m *SignOutRequest) XXX_Size() int {
	return xxx_messageInfo_SignOutRequest.Size(m)
}
func (m *SignOutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignOutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignOutRequest proto.InternalMessageInfo

func (m *SignOutRequest) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

type GetMessageRequest struct {
	Etag                 string   `protobuf:"bytes,1,opt,name=etag,proto3" json:"etag"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessageRequest) Reset()         { *m = GetMessageRequest{} }
func (m *GetMessageRequest) String() string { return proto.CompactTextString(m) }
func (*GetMessageRequest) ProtoMessage()    {}
func (*GetMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{12}
}
func (m *GetMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageRequest.Unmarshal(m, b)
}
func (m *GetMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageRequest.Marshal(b, m, deterministic)
}
func (m *GetMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageRequest.Merge(m, src)
}
func (m *GetMessageRequest) XXX_Size() int {
	return xxx_messageInfo_GetMessageRequest.Size(m)
}
func (m *GetMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageRequest proto.InternalMessageInfo

func (m *GetMessageRequest) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

type GetMessageResponse struct {
	Status               *status.Status   `protobuf:"bytes,1,opt,name=status,proto3" json:"status"`
	Gmsg                 *igm.GameMessage `protobuf:"bytes,2,opt,name=gmsg,proto3" json:"gmsg"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetMessageResponse) Reset()         { *m = GetMessageResponse{} }
func (m *GetMessageResponse) String() string { return proto.CompactTextString(m) }
func (*GetMessageResponse) ProtoMessage()    {}
func (*GetMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{13}
}
func (m *GetMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageResponse.Unmarshal(m, b)
}
func (m *GetMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageResponse.Marshal(b, m, deterministic)
}
func (m *GetMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageResponse.Merge(m, src)
}
func (m *GetMessageResponse) XXX_Size() int {
	return xxx_messageInfo_GetMessageResponse.Size(m)
}
func (m *GetMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageResponse proto.InternalMessageInfo

func (m *GetMessageResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetMessageResponse) GetGmsg() *igm.GameMessage {
	if m != nil {
		return m.Gmsg
	}
	return nil
}

type PutMessageRequest struct {
	Etag                 string             `protobuf:"bytes,1,opt,name=etag,proto3" json:"etag"`
	Pmsg                 *igm.PlayerMessage `protobuf:"bytes,2,opt,name=pmsg,proto3" json:"pmsg"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PutMessageRequest) Reset()         { *m = PutMessageRequest{} }
func (m *PutMessageRequest) String() string { return proto.CompactTextString(m) }
func (*PutMessageRequest) ProtoMessage()    {}
func (*PutMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{14}
}
func (m *PutMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutMessageRequest.Unmarshal(m, b)
}
func (m *PutMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutMessageRequest.Marshal(b, m, deterministic)
}
func (m *PutMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutMessageRequest.Merge(m, src)
}
func (m *PutMessageRequest) XXX_Size() int {
	return xxx_messageInfo_PutMessageRequest.Size(m)
}
func (m *PutMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutMessageRequest proto.InternalMessageInfo

func (m *PutMessageRequest) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

func (m *PutMessageRequest) GetPmsg() *igm.PlayerMessage {
	if m != nil {
		return m.Pmsg
	}
	return nil
}

type PMDefaultResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PMDefaultResponse) Reset()         { *m = PMDefaultResponse{} }
func (m *PMDefaultResponse) String() string { return proto.CompactTextString(m) }
func (*PMDefaultResponse) ProtoMessage()    {}
func (*PMDefaultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{15}
}
func (m *PMDefaultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PMDefaultResponse.Unmarshal(m, b)
}
func (m *PMDefaultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PMDefaultResponse.Marshal(b, m, deterministic)
}
func (m *PMDefaultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PMDefaultResponse.Merge(m, src)
}
func (m *PMDefaultResponse) XXX_Size() int {
	return xxx_messageInfo_PMDefaultResponse.Size(m)
}
func (m *PMDefaultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PMDefaultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PMDefaultResponse proto.InternalMessageInfo

func (m *PMDefaultResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*PlayerCreateRequest)(nil), "ipm.PlayerCreateRequest")
	proto.RegisterType((*PlayerCreateResponse)(nil), "ipm.PlayerCreateResponse")
	proto.RegisterType((*PlayerDeleteRequest)(nil), "ipm.PlayerDeleteRequest")
	proto.RegisterType((*PlayerListRequest)(nil), "ipm.PlayerListRequest")
	proto.RegisterType((*PlayerListResponse)(nil), "ipm.PlayerListResponse")
	proto.RegisterType((*PlayerInfo)(nil), "ipm.PlayerInfo")
	proto.RegisterType((*PlayerStartRequest)(nil), "ipm.PlayerStartRequest")
	proto.RegisterType((*PlayerStartResponse)(nil), "ipm.PlayerStartResponse")
	proto.RegisterType((*PlayerStopRequest)(nil), "ipm.PlayerStopRequest")
	proto.RegisterType((*SignInRequest)(nil), "ipm.SignInRequest")
	proto.RegisterType((*SignInResponse)(nil), "ipm.SignInResponse")
	proto.RegisterType((*SignOutRequest)(nil), "ipm.SignOutRequest")
	proto.RegisterType((*GetMessageRequest)(nil), "ipm.GetMessageRequest")
	proto.RegisterType((*GetMessageResponse)(nil), "ipm.GetMessageResponse")
	proto.RegisterType((*PutMessageRequest)(nil), "ipm.PutMessageRequest")
	proto.RegisterType((*PMDefaultResponse)(nil), "ipm.PMDefaultResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PMClient is the client API for PM service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PMClient interface {
	PlayerCreate(ctx context.Context, in *PlayerCreateRequest, opts ...grpc.CallOption) (*PlayerCreateResponse, error)
	PlayerDelete(ctx context.Context, in *PlayerDeleteRequest, opts ...grpc.CallOption) (*PMDefaultResponse, error)
	PlayerList(ctx context.Context, in *PlayerListRequest, opts ...grpc.CallOption) (*PlayerListResponse, error)
	PlayerStart(ctx context.Context, in *PlayerStartRequest, opts ...grpc.CallOption) (*PlayerStartResponse, error)
	PlayerStop(ctx context.Context, in *PlayerStopRequest, opts ...grpc.CallOption) (*PMDefaultResponse, error)
}

type pMClient struct {
	cc *grpc.ClientConn
}

func NewPMClient(cc *grpc.ClientConn) PMClient {
	return &pMClient{cc}
}

func (c *pMClient) PlayerCreate(ctx context.Context, in *PlayerCreateRequest, opts ...grpc.CallOption) (*PlayerCreateResponse, error) {
	out := new(PlayerCreateResponse)
	err := c.cc.Invoke(ctx, "/ipm.PM/CreatePlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pMClient) PlayerDelete(ctx context.Context, in *PlayerDeleteRequest, opts ...grpc.CallOption) (*PMDefaultResponse, error) {
	out := new(PMDefaultResponse)
	err := c.cc.Invoke(ctx, "/ipm.PM/PlayerDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pMClient) PlayerList(ctx context.Context, in *PlayerListRequest, opts ...grpc.CallOption) (*PlayerListResponse, error) {
	out := new(PlayerListResponse)
	err := c.cc.Invoke(ctx, "/ipm.PM/PlayerList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pMClient) PlayerStart(ctx context.Context, in *PlayerStartRequest, opts ...grpc.CallOption) (*PlayerStartResponse, error) {
	out := new(PlayerStartResponse)
	err := c.cc.Invoke(ctx, "/ipm.PM/PlayerStart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pMClient) PlayerStop(ctx context.Context, in *PlayerStopRequest, opts ...grpc.CallOption) (*PMDefaultResponse, error) {
	out := new(PMDefaultResponse)
	err := c.cc.Invoke(ctx, "/ipm.PM/PlayerStop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PMServer is the server API for PM service.
type PMServer interface {
	PlayerCreate(context.Context, *PlayerCreateRequest) (*PlayerCreateResponse, error)
	PlayerDelete(context.Context, *PlayerDeleteRequest) (*PMDefaultResponse, error)
	PlayerList(context.Context, *PlayerListRequest) (*PlayerListResponse, error)
	PlayerStart(context.Context, *PlayerStartRequest) (*PlayerStartResponse, error)
	PlayerStop(context.Context, *PlayerStopRequest) (*PMDefaultResponse, error)
}

func RegisterPMServer(s *grpc.Server, srv PMServer) {
	s.RegisterService(&_PM_serviceDesc, srv)
}

func _PM_PlayerCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PMServer).PlayerCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipm.PM/CreatePlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PMServer).PlayerCreate(ctx, req.(*PlayerCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PM_PlayerDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PMServer).PlayerDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipm.PM/PlayerDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PMServer).PlayerDelete(ctx, req.(*PlayerDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PM_PlayerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PMServer).PlayerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipm.PM/PlayerList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PMServer).PlayerList(ctx, req.(*PlayerListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PM_PlayerStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PMServer).PlayerStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipm.PM/PlayerStart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PMServer).PlayerStart(ctx, req.(*PlayerStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PM_PlayerStop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PMServer).PlayerStop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipm.PM/PlayerStop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PMServer).PlayerStop(ctx, req.(*PlayerStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PM_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ipm.PM",
	HandlerType: (*PMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePlayer",
			Handler:    _PM_PlayerCreate_Handler,
		},
		{
			MethodName: "PlayerDelete",
			Handler:    _PM_PlayerDelete_Handler,
		},
		{
			MethodName: "PlayerList",
			Handler:    _PM_PlayerList_Handler,
		},
		{
			MethodName: "PlayerStart",
			Handler:    _PM_PlayerStart_Handler,
		},
		{
			MethodName: "PlayerStop",
			Handler:    _PM_PlayerStop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pm/pm.proto",
}

// PlayerClient is the client API for Player service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlayerClient interface {
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error)
	SignOut(ctx context.Context, in *SignOutRequest, opts ...grpc.CallOption) (*PMDefaultResponse, error)
	GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageResponse, error)
	PutMessage(ctx context.Context, in *PutMessageRequest, opts ...grpc.CallOption) (*PMDefaultResponse, error)
}

type playerClient struct {
	cc *grpc.ClientConn
}

func NewPlayerClient(cc *grpc.ClientConn) PlayerClient {
	return &playerClient{cc}
}

func (c *playerClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/ipm.Player/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerClient) SignOut(ctx context.Context, in *SignOutRequest, opts ...grpc.CallOption) (*PMDefaultResponse, error) {
	out := new(PMDefaultResponse)
	err := c.cc.Invoke(ctx, "/ipm.Player/SignOut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerClient) GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageResponse, error) {
	out := new(GetMessageResponse)
	err := c.cc.Invoke(ctx, "/ipm.Player/GetMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerClient) PutMessage(ctx context.Context, in *PutMessageRequest, opts ...grpc.CallOption) (*PMDefaultResponse, error) {
	out := new(PMDefaultResponse)
	err := c.cc.Invoke(ctx, "/ipm.Player/PutMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayerServer is the server API for Player service.
type PlayerServer interface {
	SignIn(context.Context, *SignInRequest) (*SignInResponse, error)
	SignOut(context.Context, *SignOutRequest) (*PMDefaultResponse, error)
	GetMessage(context.Context, *GetMessageRequest) (*GetMessageResponse, error)
	PutMessage(context.Context, *PutMessageRequest) (*PMDefaultResponse, error)
}

func RegisterPlayerServer(s *grpc.Server, srv PlayerServer) {
	s.RegisterService(&_Player_serviceDesc, srv)
}

func _Player_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipm.Player/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Player_SignOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServer).SignOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipm.Player/SignOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServer).SignOut(ctx, req.(*SignOutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Player_GetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServer).GetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipm.Player/GetMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServer).GetMessage(ctx, req.(*GetMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Player_PutMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServer).PutMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipm.Player/PutMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServer).PutMessage(ctx, req.(*PutMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Player_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ipm.Player",
	HandlerType: (*PlayerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignIn",
			Handler:    _Player_SignIn_Handler,
		},
		{
			MethodName: "SignOut",
			Handler:    _Player_SignOut_Handler,
		},
		{
			MethodName: "GetMessage",
			Handler:    _Player_GetMessage_Handler,
		},
		{
			MethodName: "PutMessage",
			Handler:    _Player_PutMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pm/pm.proto",
}

func init() { proto.RegisterFile("pm/pm.proto", fileDescriptor_8af9a1f56cafcd39) }

var fileDescriptor_8af9a1f56cafcd39 = []byte{
	// 568 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0x3f, 0x48, 0xe9, 0x18, 0x4a, 0x33, 0x45, 0xc5, 0xf8, 0x14, 0x59, 0x25, 0x0d, 0x17,
	0x47, 0x4a, 0x2f, 0x48, 0x08, 0x2a, 0x95, 0xa2, 0xaa, 0x52, 0xa3, 0x46, 0xc9, 0x8d, 0xdb, 0x46,
	0xdd, 0x5a, 0x16, 0x71, 0xbc, 0x78, 0xd7, 0x42, 0xfc, 0x0f, 0x7e, 0x1a, 0x3f, 0x86, 0x23, 0xf2,
	0xae, 0x37, 0x5e, 0xd7, 0x38, 0x22, 0x07, 0x4e, 0xde, 0xcc, 0xbc, 0xbc, 0x79, 0x33, 0x3b, 0xcf,
	0x06, 0x8f, 0xa5, 0x63, 0x96, 0x46, 0x2c, 0xcf, 0x44, 0x86, 0x4e, 0xc2, 0xd2, 0xe0, 0x98, 0x0b,
	0x22, 0x0a, 0x3e, 0x56, 0x0f, 0x95, 0x09, 0xbc, 0x38, 0x1d, 0xc7, 0x15, 0x2c, 0xfc, 0x0a, 0xc7,
	0xb3, 0x15, 0xf9, 0x41, 0xf3, 0x4f, 0x39, 0x25, 0x82, 0xce, 0xe9, 0xb7, 0x82, 0x72, 0x81, 0x47,
	0xe0, 0xb0, 0xe4, 0xde, 0xb7, 0x06, 0xd6, 0xe8, 0x60, 0x5e, 0x1e, 0x11, 0xc1, 0x5d, 0x93, 0x94,
	0xfa, 0xb6, 0x0c, 0xc9, 0x33, 0x06, 0xf0, 0x94, 0x11, 0xce, 0xbf, 0x67, 0xf9, 0xbd, 0xef, 0xc8,
	0xf8, 0xe6, 0x77, 0x89, 0x67, 0x59, 0x2e, 0x7c, 0x77, 0x60, 0x8d, 0x9c, 0xb9, 0x3c, 0x87, 0x3f,
	0x2d, 0x78, 0xd9, 0xac, 0xc6, 0x59, 0xb6, 0xe6, 0x14, 0x87, 0xd0, 0x53, 0x12, 0x65, 0x45, 0x6f,
	0x72, 0x18, 0x55, 0x8a, 0x17, 0xf2, 0x31, 0xaf, 0xb2, 0x5a, 0x96, 0xdd, 0x96, 0xe5, 0x74, 0xc8,
	0x72, 0x3b, 0x64, 0x3d, 0x31, 0x64, 0x9d, 0xe9, 0x19, 0x5c, 0xd1, 0x15, 0xdd, 0x32, 0x83, 0xf0,
	0x0d, 0xf4, 0x15, 0xf0, 0x36, 0xe1, 0xa2, 0x1b, 0x16, 0x03, 0x9a, 0xb0, 0x1d, 0x7b, 0x7c, 0x0b,
	0xfb, 0x4c, 0xfe, 0x9b, 0xfb, 0xf6, 0xc0, 0x19, 0x79, 0x93, 0x17, 0x51, 0xc2, 0xd2, 0x48, 0x31,
	0xde, 0xac, 0x1f, 0xb2, 0xb9, 0xce, 0x87, 0x4b, 0x80, 0x3a, 0xfc, 0x9f, 0xee, 0x6c, 0xa8, 0x9b,
	0x59, 0x08, 0x92, 0x6f, 0x69, 0xfa, 0x83, 0x1e, 0x62, 0x85, 0xdb, 0xad, 0xeb, 0x7a, 0xb4, 0x0b,
	0x91, 0xb1, 0xee, 0x2a, 0x17, 0xf0, 0x7c, 0x91, 0xc4, 0xeb, 0x9b, 0xb5, 0x86, 0xe8, 0x16, 0xad,
	0x8e, 0x16, 0xed, 0x66, 0x8b, 0xe1, 0x2d, 0x1c, 0x6a, 0x82, 0x1d, 0xef, 0x05, 0xc1, 0xa5, 0x82,
	0xc4, 0x7a, 0x98, 0xe5, 0x39, 0x3c, 0x55, 0x6c, 0x77, 0x85, 0x30, 0xf4, 0x48, 0x94, 0x65, 0xa0,
	0xce, 0xa0, 0x7f, 0x4d, 0xc5, 0x94, 0x72, 0x4e, 0x62, 0xba, 0x0d, 0xb8, 0x04, 0x34, 0x81, 0x3b,
	0x0a, 0x3c, 0x05, 0x37, 0x4e, 0xb9, 0x12, 0xe8, 0x4d, 0x8e, 0xa2, 0x24, 0x4e, 0xa3, 0x6b, 0x92,
	0x52, 0xcd, 0x27, 0xb3, 0xe1, 0x1d, 0xf4, 0x67, 0xc5, 0x3f, 0x88, 0xc1, 0x21, 0xb8, 0xac, 0xa6,
	0x43, 0x49, 0xa7, 0xae, 0x68, 0x43, 0x58, 0xe6, 0xc3, 0xf7, 0xd0, 0x9f, 0x4d, 0xaf, 0xe8, 0x03,
	0x29, 0x56, 0x3b, 0x5f, 0xfb, 0xe4, 0x97, 0x0d, 0xf6, 0x6c, 0x8a, 0x9f, 0xe1, 0x99, 0xf9, 0x5e,
	0x40, 0xdf, 0x58, 0xf9, 0xc6, 0x8b, 0x29, 0x78, 0xfd, 0x97, 0x8c, 0xaa, 0x19, 0xee, 0xe1, 0xa5,
	0xa6, 0x51, 0x46, 0x6e, 0xd0, 0x34, 0xbc, 0x1d, 0x9c, 0xa8, 0xcc, 0x63, 0xdd, 0xe1, 0x1e, 0x5e,
	0x68, 0x4f, 0x95, 0xe6, 0xc5, 0x13, 0x83, 0xc1, 0x30, 0x7d, 0xf0, 0xaa, 0x15, 0x37, 0x44, 0x78,
	0x86, 0x11, 0xd0, 0x44, 0x9a, 0x16, 0x0a, 0xfc, 0x76, 0x62, 0xc3, 0xf1, 0x51, 0x8b, 0x28, 0xdd,
	0xd0, 0x10, 0x61, 0xd8, 0xa3, 0xbb, 0x89, 0xc9, 0x6f, 0x0b, 0x7a, 0x0a, 0x8f, 0xe7, 0xd0, 0x53,
	0x0b, 0x8f, 0x28, 0xe1, 0x0d, 0xfb, 0x04, 0xc7, 0x8d, 0xd8, 0xa6, 0xfe, 0x3b, 0xd8, 0xaf, 0xf6,
	0x1a, 0x6b, 0x44, 0xbd, 0xe5, 0xdb, 0xc7, 0x57, 0xaf, 0x70, 0xa5, 0xbc, 0xb5, 0xfc, 0xd5, 0xf8,
	0xda, 0xbb, 0x5e, 0xb5, 0x5e, 0x3c, 0x22, 0x68, 0x2d, 0x6c, 0xb7, 0x80, 0xcb, 0x83, 0x2f, 0xfb,
	0x84, 0x25, 0xe3, 0x84, 0xa5, 0xcb, 0x9e, 0xfc, 0xc4, 0x9d, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff,
	0x21, 0xff, 0xa7, 0x94, 0x18, 0x07, 0x00, 0x00,
}
