// Code generated by protoc-gen-go. DO NOT EDIT.
// source: status/status.proto

package status

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	MessageCn            string   `protobuf:"bytes,3,opt,name=messageCn,proto3" json:"messageCn"`
	Stack                []string `protobuf:"bytes,4,rep,name=stack,proto3" json:"stack"`
	Desc                 string   `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc"`
	UUID                 string   `protobuf:"bytes,6,opt,name=UUID,proto3" json:"UUID"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_979164913cd1534b, []int{0}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Status) GetMessageCn() string {
	if m != nil {
		return m.MessageCn
	}
	return ""
}

func (m *Status) GetStack() []string {
	if m != nil {
		return m.Stack
	}
	return nil
}

func (m *Status) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Status) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func init() {
	proto.RegisterType((*Status)(nil), "status.Status")
}

func init() { proto.RegisterFile("status/status.proto", fileDescriptor_979164913cd1534b) }

var fileDescriptor_979164913cd1534b = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x2e, 0x49, 0x2c,
	0x29, 0x2d, 0xd6, 0x87, 0x50, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10, 0x9e, 0xd2,
	0x24, 0x46, 0x2e, 0xb6, 0x60, 0x30, 0x53, 0x48, 0x88, 0x8b, 0x25, 0x39, 0x3f, 0x25, 0x55, 0x82,
	0x51, 0x81, 0x51, 0x83, 0x35, 0x08, 0xcc, 0x16, 0x92, 0xe0, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e,
	0x4c, 0x4f, 0x95, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71, 0x85, 0x64, 0xb8, 0x38, 0xa1,
	0x4c, 0xe7, 0x3c, 0x09, 0x66, 0xb0, 0x1c, 0x42, 0x40, 0x48, 0x84, 0x8b, 0xb5, 0xb8, 0x24, 0x31,
	0x39, 0x5b, 0x82, 0x45, 0x81, 0x59, 0x83, 0x33, 0x08, 0xc2, 0x01, 0xd9, 0x90, 0x92, 0x5a, 0x9c,
	0x2c, 0xc1, 0x0a, 0x56, 0x0e, 0x66, 0x83, 0xc4, 0x42, 0x43, 0x3d, 0x5d, 0x24, 0xd8, 0x20, 0x62,
	0x20, 0xb6, 0x13, 0x47, 0x14, 0xd4, 0x79, 0x49, 0x6c, 0x60, 0xd7, 0x1a, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x93, 0xfc, 0x92, 0x85, 0xc4, 0x00, 0x00, 0x00,
}
