// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pm/pm.proto

package ipm

import (
	igm "api/igm"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	status "status"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PlayerCreateRequest struct {
	Pid                  string   `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerCreateRequest) Reset()         { *m = PlayerCreateRequest{} }
func (m *PlayerCreateRequest) String() string { return proto.CompactTextString(m) }
func (*PlayerCreateRequest) ProtoMessage()    {}
func (*PlayerCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{0}
}
func (m *PlayerCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerCreateRequest.Unmarshal(m, b)
}
func (m *PlayerCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerCreateRequest.Marshal(b, m, deterministic)
}
func (m *PlayerCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerCreateRequest.Merge(m, src)
}
func (m *PlayerCreateRequest) XXX_Size() int {
	return xxx_messageInfo_PlayerCreateRequest.Size(m)
}
func (m *PlayerCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerCreateRequest proto.InternalMessageInfo

func (m *PlayerCreateRequest) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *PlayerCreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlayerCreateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type PlayerCreateResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status"`
	Player               *PlayerInfo    `protobuf:"bytes,2,opt,name=player,proto3" json:"player"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PlayerCreateResponse) Reset()         { *m = PlayerCreateResponse{} }
func (m *PlayerCreateResponse) String() string { return proto.CompactTextString(m) }
func (*PlayerCreateResponse) ProtoMessage()    {}
func (*PlayerCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{1}
}
func (m *PlayerCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerCreateResponse.Unmarshal(m, b)
}
func (m *PlayerCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerCreateResponse.Marshal(b, m, deterministic)
}
func (m *PlayerCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerCreateResponse.Merge(m, src)
}
func (m *PlayerCreateResponse) XXX_Size() int {
	return xxx_messageInfo_PlayerCreateResponse.Size(m)
}
func (m *PlayerCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerCreateResponse proto.InternalMessageInfo

func (m *PlayerCreateResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *PlayerCreateResponse) GetPlayer() *PlayerInfo {
	if m != nil {
		return m.Player
	}
	return nil
}

type PlayerDeleteRequest struct {
	Pid                  string   `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerDeleteRequest) Reset()         { *m = PlayerDeleteRequest{} }
func (m *PlayerDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*PlayerDeleteRequest) ProtoMessage()    {}
func (*PlayerDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{2}
}
func (m *PlayerDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerDeleteRequest.Unmarshal(m, b)
}
func (m *PlayerDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerDeleteRequest.Marshal(b, m, deterministic)
}
func (m *PlayerDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerDeleteRequest.Merge(m, src)
}
func (m *PlayerDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_PlayerDeleteRequest.Size(m)
}
func (m *PlayerDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerDeleteRequest proto.InternalMessageInfo

func (m *PlayerDeleteRequest) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

type PlayerListRequest struct {
	Pid                  string   `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerListRequest) Reset()         { *m = PlayerListRequest{} }
func (m *PlayerListRequest) String() string { return proto.CompactTextString(m) }
func (*PlayerListRequest) ProtoMessage()    {}
func (*PlayerListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{3}
}
func (m *PlayerListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerListRequest.Unmarshal(m, b)
}
func (m *PlayerListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerListRequest.Marshal(b, m, deterministic)
}
func (m *PlayerListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerListRequest.Merge(m, src)
}
func (m *PlayerListRequest) XXX_Size() int {
	return xxx_messageInfo_PlayerListRequest.Size(m)
}
func (m *PlayerListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerListRequest proto.InternalMessageInfo

func (m *PlayerListRequest) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

type PlayerListResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status"`
	Players              []*PlayerInfo  `protobuf:"bytes,2,rep,name=players,proto3" json:"players"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PlayerListResponse) Reset()         { *m = PlayerListResponse{} }
func (m *PlayerListResponse) String() string { return proto.CompactTextString(m) }
func (*PlayerListResponse) ProtoMessage()    {}
func (*PlayerListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{4}
}
func (m *PlayerListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerListResponse.Unmarshal(m, b)
}
func (m *PlayerListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerListResponse.Marshal(b, m, deterministic)
}
func (m *PlayerListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerListResponse.Merge(m, src)
}
func (m *PlayerListResponse) XXX_Size() int {
	return xxx_messageInfo_PlayerListResponse.Size(m)
}
func (m *PlayerListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerListResponse proto.InternalMessageInfo

func (m *PlayerListResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *PlayerListResponse) GetPlayers() []*PlayerInfo {
	if m != nil {
		return m.Players
	}
	return nil
}

type PlayerInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password"`
	Etag                 string   `protobuf:"bytes,4,opt,name=etag,proto3" json:"etag"`
	Port                 int64    `protobuf:"varint,5,opt,name=port,proto3" json:"port"`
	Pid                  int64    `protobuf:"varint,6,opt,name=pid,proto3" json:"pid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{5}
}
func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(m, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PlayerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlayerInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *PlayerInfo) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

func (m *PlayerInfo) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *PlayerInfo) GetPid() int64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

type PlayerSignInRequest struct {
	Pid                  string   `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerSignInRequest) Reset()         { *m = PlayerSignInRequest{} }
func (m *PlayerSignInRequest) String() string { return proto.CompactTextString(m) }
func (*PlayerSignInRequest) ProtoMessage()    {}
func (*PlayerSignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{6}
}
func (m *PlayerSignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerSignInRequest.Unmarshal(m, b)
}
func (m *PlayerSignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerSignInRequest.Marshal(b, m, deterministic)
}
func (m *PlayerSignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerSignInRequest.Merge(m, src)
}
func (m *PlayerSignInRequest) XXX_Size() int {
	return xxx_messageInfo_PlayerSignInRequest.Size(m)
}
func (m *PlayerSignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerSignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerSignInRequest proto.InternalMessageInfo

func (m *PlayerSignInRequest) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *PlayerSignInRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlayerSignInRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type PlayerSignInResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status"`
	Port                 int64          `protobuf:"varint,2,opt,name=port,proto3" json:"port"`
	Etag                 string         `protobuf:"bytes,3,opt,name=etag,proto3" json:"etag"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PlayerSignInResponse) Reset()         { *m = PlayerSignInResponse{} }
func (m *PlayerSignInResponse) String() string { return proto.CompactTextString(m) }
func (*PlayerSignInResponse) ProtoMessage()    {}
func (*PlayerSignInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{7}
}
func (m *PlayerSignInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerSignInResponse.Unmarshal(m, b)
}
func (m *PlayerSignInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerSignInResponse.Marshal(b, m, deterministic)
}
func (m *PlayerSignInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerSignInResponse.Merge(m, src)
}
func (m *PlayerSignInResponse) XXX_Size() int {
	return xxx_messageInfo_PlayerSignInResponse.Size(m)
}
func (m *PlayerSignInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerSignInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerSignInResponse proto.InternalMessageInfo

func (m *PlayerSignInResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *PlayerSignInResponse) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *PlayerSignInResponse) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

type PlayerSignOutRequest struct {
	Pid                  string   `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid"`
	Etag                 string   `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerSignOutRequest) Reset()         { *m = PlayerSignOutRequest{} }
func (m *PlayerSignOutRequest) String() string { return proto.CompactTextString(m) }
func (*PlayerSignOutRequest) ProtoMessage()    {}
func (*PlayerSignOutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{8}
}
func (m *PlayerSignOutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerSignOutRequest.Unmarshal(m, b)
}
func (m *PlayerSignOutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerSignOutRequest.Marshal(b, m, deterministic)
}
func (m *PlayerSignOutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerSignOutRequest.Merge(m, src)
}
func (m *PlayerSignOutRequest) XXX_Size() int {
	return xxx_messageInfo_PlayerSignOutRequest.Size(m)
}
func (m *PlayerSignOutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerSignOutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerSignOutRequest proto.InternalMessageInfo

func (m *PlayerSignOutRequest) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *PlayerSignOutRequest) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

type AttachRequest struct {
	Etag                 string   `protobuf:"bytes,1,opt,name=etag,proto3" json:"etag"`
	Pid                  string   `protobuf:"bytes,2,opt,name=pid,proto3" json:"pid"`
	GamePort             string   `protobuf:"bytes,3,opt,name=gamePort,proto3" json:"gamePort"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachRequest) Reset()         { *m = AttachRequest{} }
func (m *AttachRequest) String() string { return proto.CompactTextString(m) }
func (*AttachRequest) ProtoMessage()    {}
func (*AttachRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{9}
}
func (m *AttachRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachRequest.Unmarshal(m, b)
}
func (m *AttachRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachRequest.Marshal(b, m, deterministic)
}
func (m *AttachRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachRequest.Merge(m, src)
}
func (m *AttachRequest) XXX_Size() int {
	return xxx_messageInfo_AttachRequest.Size(m)
}
func (m *AttachRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AttachRequest proto.InternalMessageInfo

func (m *AttachRequest) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

func (m *AttachRequest) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *AttachRequest) GetGamePort() string {
	if m != nil {
		return m.GamePort
	}
	return ""
}

type DetachRequest struct {
	Etag                 string   `protobuf:"bytes,1,opt,name=etag,proto3" json:"etag"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetachRequest) Reset()         { *m = DetachRequest{} }
func (m *DetachRequest) String() string { return proto.CompactTextString(m) }
func (*DetachRequest) ProtoMessage()    {}
func (*DetachRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{10}
}
func (m *DetachRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetachRequest.Unmarshal(m, b)
}
func (m *DetachRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetachRequest.Marshal(b, m, deterministic)
}
func (m *DetachRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetachRequest.Merge(m, src)
}
func (m *DetachRequest) XXX_Size() int {
	return xxx_messageInfo_DetachRequest.Size(m)
}
func (m *DetachRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetachRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetachRequest proto.InternalMessageInfo

func (m *DetachRequest) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

type GetMessageRequest struct {
	Etag                 string   `protobuf:"bytes,1,opt,name=etag,proto3" json:"etag"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessageRequest) Reset()         { *m = GetMessageRequest{} }
func (m *GetMessageRequest) String() string { return proto.CompactTextString(m) }
func (*GetMessageRequest) ProtoMessage()    {}
func (*GetMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{11}
}
func (m *GetMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageRequest.Unmarshal(m, b)
}
func (m *GetMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageRequest.Marshal(b, m, deterministic)
}
func (m *GetMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageRequest.Merge(m, src)
}
func (m *GetMessageRequest) XXX_Size() int {
	return xxx_messageInfo_GetMessageRequest.Size(m)
}
func (m *GetMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageRequest proto.InternalMessageInfo

func (m *GetMessageRequest) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

type GetMessageResponse struct {
	Status               *status.Status   `protobuf:"bytes,1,opt,name=status,proto3" json:"status"`
	Gmsg                 *igm.GameMessage `protobuf:"bytes,2,opt,name=gmsg,proto3" json:"gmsg"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetMessageResponse) Reset()         { *m = GetMessageResponse{} }
func (m *GetMessageResponse) String() string { return proto.CompactTextString(m) }
func (*GetMessageResponse) ProtoMessage()    {}
func (*GetMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{12}
}
func (m *GetMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageResponse.Unmarshal(m, b)
}
func (m *GetMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageResponse.Marshal(b, m, deterministic)
}
func (m *GetMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageResponse.Merge(m, src)
}
func (m *GetMessageResponse) XXX_Size() int {
	return xxx_messageInfo_GetMessageResponse.Size(m)
}
func (m *GetMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageResponse proto.InternalMessageInfo

func (m *GetMessageResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetMessageResponse) GetGmsg() *igm.GameMessage {
	if m != nil {
		return m.Gmsg
	}
	return nil
}

type PutMessageRequest struct {
	Etag                 string             `protobuf:"bytes,1,opt,name=etag,proto3" json:"etag"`
	Pmsg                 *igm.PlayerMessage `protobuf:"bytes,2,opt,name=pmsg,proto3" json:"pmsg"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PutMessageRequest) Reset()         { *m = PutMessageRequest{} }
func (m *PutMessageRequest) String() string { return proto.CompactTextString(m) }
func (*PutMessageRequest) ProtoMessage()    {}
func (*PutMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{13}
}
func (m *PutMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutMessageRequest.Unmarshal(m, b)
}
func (m *PutMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutMessageRequest.Marshal(b, m, deterministic)
}
func (m *PutMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutMessageRequest.Merge(m, src)
}
func (m *PutMessageRequest) XXX_Size() int {
	return xxx_messageInfo_PutMessageRequest.Size(m)
}
func (m *PutMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutMessageRequest proto.InternalMessageInfo

func (m *PutMessageRequest) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

func (m *PutMessageRequest) GetPmsg() *igm.PlayerMessage {
	if m != nil {
		return m.Pmsg
	}
	return nil
}

type PMDefaultResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PMDefaultResponse) Reset()         { *m = PMDefaultResponse{} }
func (m *PMDefaultResponse) String() string { return proto.CompactTextString(m) }
func (*PMDefaultResponse) ProtoMessage()    {}
func (*PMDefaultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8af9a1f56cafcd39, []int{14}
}
func (m *PMDefaultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PMDefaultResponse.Unmarshal(m, b)
}
func (m *PMDefaultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PMDefaultResponse.Marshal(b, m, deterministic)
}
func (m *PMDefaultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PMDefaultResponse.Merge(m, src)
}
func (m *PMDefaultResponse) XXX_Size() int {
	return xxx_messageInfo_PMDefaultResponse.Size(m)
}
func (m *PMDefaultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PMDefaultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PMDefaultResponse proto.InternalMessageInfo

func (m *PMDefaultResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*PlayerCreateRequest)(nil), "ipm.PlayerCreateRequest")
	proto.RegisterType((*PlayerCreateResponse)(nil), "ipm.PlayerCreateResponse")
	proto.RegisterType((*PlayerDeleteRequest)(nil), "ipm.PlayerDeleteRequest")
	proto.RegisterType((*PlayerListRequest)(nil), "ipm.PlayerListRequest")
	proto.RegisterType((*PlayerListResponse)(nil), "ipm.PlayerListResponse")
	proto.RegisterType((*PlayerInfo)(nil), "ipm.PlayerInfo")
	proto.RegisterType((*PlayerSignInRequest)(nil), "ipm.PlayerSignInRequest")
	proto.RegisterType((*PlayerSignInResponse)(nil), "ipm.PlayerSignInResponse")
	proto.RegisterType((*PlayerSignOutRequest)(nil), "ipm.PlayerSignOutRequest")
	proto.RegisterType((*AttachRequest)(nil), "ipm.AttachRequest")
	proto.RegisterType((*DetachRequest)(nil), "ipm.DetachRequest")
	proto.RegisterType((*GetMessageRequest)(nil), "ipm.GetMessageRequest")
	proto.RegisterType((*GetMessageResponse)(nil), "ipm.GetMessageResponse")
	proto.RegisterType((*PutMessageRequest)(nil), "ipm.PutMessageRequest")
	proto.RegisterType((*PMDefaultResponse)(nil), "ipm.PMDefaultResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PMClient is the client API for PM service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PMClient interface {
	PlayerCreate(ctx context.Context, in *PlayerCreateRequest, opts ...grpc.CallOption) (*PlayerCreateResponse, error)
	PlayerDelete(ctx context.Context, in *PlayerDeleteRequest, opts ...grpc.CallOption) (*PMDefaultResponse, error)
	PlayerList(ctx context.Context, in *PlayerListRequest, opts ...grpc.CallOption) (*PlayerListResponse, error)
	PlayerSignIn(ctx context.Context, in *PlayerSignInRequest, opts ...grpc.CallOption) (*PlayerSignInResponse, error)
	PlayerSignOut(ctx context.Context, in *PlayerSignOutRequest, opts ...grpc.CallOption) (*PMDefaultResponse, error)
}

type pMClient struct {
	cc *grpc.ClientConn
}

func NewPMClient(cc *grpc.ClientConn) PMClient {
	return &pMClient{cc}
}

func (c *pMClient) PlayerCreate(ctx context.Context, in *PlayerCreateRequest, opts ...grpc.CallOption) (*PlayerCreateResponse, error) {
	out := new(PlayerCreateResponse)
	err := c.cc.Invoke(ctx, "/ipm.PM/PlayerCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pMClient) PlayerDelete(ctx context.Context, in *PlayerDeleteRequest, opts ...grpc.CallOption) (*PMDefaultResponse, error) {
	out := new(PMDefaultResponse)
	err := c.cc.Invoke(ctx, "/ipm.PM/PlayerDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pMClient) PlayerList(ctx context.Context, in *PlayerListRequest, opts ...grpc.CallOption) (*PlayerListResponse, error) {
	out := new(PlayerListResponse)
	err := c.cc.Invoke(ctx, "/ipm.PM/PlayerList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pMClient) PlayerSignIn(ctx context.Context, in *PlayerSignInRequest, opts ...grpc.CallOption) (*PlayerSignInResponse, error) {
	out := new(PlayerSignInResponse)
	err := c.cc.Invoke(ctx, "/ipm.PM/PlayerSignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pMClient) PlayerSignOut(ctx context.Context, in *PlayerSignOutRequest, opts ...grpc.CallOption) (*PMDefaultResponse, error) {
	out := new(PMDefaultResponse)
	err := c.cc.Invoke(ctx, "/ipm.PM/PlayerSignOut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PMServer is the server API for PM service.
type PMServer interface {
	PlayerCreate(context.Context, *PlayerCreateRequest) (*PlayerCreateResponse, error)
	PlayerDelete(context.Context, *PlayerDeleteRequest) (*PMDefaultResponse, error)
	PlayerList(context.Context, *PlayerListRequest) (*PlayerListResponse, error)
	PlayerSignIn(context.Context, *PlayerSignInRequest) (*PlayerSignInResponse, error)
	PlayerSignOut(context.Context, *PlayerSignOutRequest) (*PMDefaultResponse, error)
}

func RegisterPMServer(s *grpc.Server, srv PMServer) {
	s.RegisterService(&_PM_serviceDesc, srv)
}

func _PM_PlayerCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PMServer).PlayerCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipm.PM/PlayerCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PMServer).PlayerCreate(ctx, req.(*PlayerCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PM_PlayerDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PMServer).PlayerDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipm.PM/PlayerDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PMServer).PlayerDelete(ctx, req.(*PlayerDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PM_PlayerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PMServer).PlayerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipm.PM/PlayerList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PMServer).PlayerList(ctx, req.(*PlayerListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PM_PlayerSignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerSignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PMServer).PlayerSignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipm.PM/PlayerSignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PMServer).PlayerSignIn(ctx, req.(*PlayerSignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PM_PlayerSignOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerSignOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PMServer).PlayerSignOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipm.PM/PlayerSignOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PMServer).PlayerSignOut(ctx, req.(*PlayerSignOutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PM_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ipm.PM",
	HandlerType: (*PMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlayerCreate",
			Handler:    _PM_PlayerCreate_Handler,
		},
		{
			MethodName: "PlayerDelete",
			Handler:    _PM_PlayerDelete_Handler,
		},
		{
			MethodName: "PlayerList",
			Handler:    _PM_PlayerList_Handler,
		},
		{
			MethodName: "PlayerSignIn",
			Handler:    _PM_PlayerSignIn_Handler,
		},
		{
			MethodName: "PlayerSignOut",
			Handler:    _PM_PlayerSignOut_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pm/pm.proto",
}

// PlayerClient is the client API for Player service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlayerClient interface {
	SyncInfo(ctx context.Context, in *PlayerInfo, opts ...grpc.CallOption) (*PlayerInfo, error)
	Stop(ctx context.Context, in *PlayerInfo, opts ...grpc.CallOption) (*PMDefaultResponse, error)
	Attach(ctx context.Context, in *AttachRequest, opts ...grpc.CallOption) (*PMDefaultResponse, error)
	Detach(ctx context.Context, in *DetachRequest, opts ...grpc.CallOption) (*PMDefaultResponse, error)
	GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageResponse, error)
	PutMessage(ctx context.Context, in *PutMessageRequest, opts ...grpc.CallOption) (*PMDefaultResponse, error)
}

type playerClient struct {
	cc *grpc.ClientConn
}

func NewPlayerClient(cc *grpc.ClientConn) PlayerClient {
	return &playerClient{cc}
}

func (c *playerClient) SyncInfo(ctx context.Context, in *PlayerInfo, opts ...grpc.CallOption) (*PlayerInfo, error) {
	out := new(PlayerInfo)
	err := c.cc.Invoke(ctx, "/ipm.Player/SyncInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerClient) Stop(ctx context.Context, in *PlayerInfo, opts ...grpc.CallOption) (*PMDefaultResponse, error) {
	out := new(PMDefaultResponse)
	err := c.cc.Invoke(ctx, "/ipm.Player/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerClient) Attach(ctx context.Context, in *AttachRequest, opts ...grpc.CallOption) (*PMDefaultResponse, error) {
	out := new(PMDefaultResponse)
	err := c.cc.Invoke(ctx, "/ipm.Player/Attach", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerClient) Detach(ctx context.Context, in *DetachRequest, opts ...grpc.CallOption) (*PMDefaultResponse, error) {
	out := new(PMDefaultResponse)
	err := c.cc.Invoke(ctx, "/ipm.Player/Detach", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerClient) GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageResponse, error) {
	out := new(GetMessageResponse)
	err := c.cc.Invoke(ctx, "/ipm.Player/GetMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerClient) PutMessage(ctx context.Context, in *PutMessageRequest, opts ...grpc.CallOption) (*PMDefaultResponse, error) {
	out := new(PMDefaultResponse)
	err := c.cc.Invoke(ctx, "/ipm.Player/PutMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayerServer is the server API for Player service.
type PlayerServer interface {
	SyncInfo(context.Context, *PlayerInfo) (*PlayerInfo, error)
	Stop(context.Context, *PlayerInfo) (*PMDefaultResponse, error)
	Attach(context.Context, *AttachRequest) (*PMDefaultResponse, error)
	Detach(context.Context, *DetachRequest) (*PMDefaultResponse, error)
	GetMessage(context.Context, *GetMessageRequest) (*GetMessageResponse, error)
	PutMessage(context.Context, *PutMessageRequest) (*PMDefaultResponse, error)
}

func RegisterPlayerServer(s *grpc.Server, srv PlayerServer) {
	s.RegisterService(&_Player_serviceDesc, srv)
}

func _Player_SyncInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServer).SyncInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipm.Player/SyncInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServer).SyncInfo(ctx, req.(*PlayerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Player_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipm.Player/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServer).Stop(ctx, req.(*PlayerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Player_Attach_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServer).Attach(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipm.Player/Attach",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServer).Attach(ctx, req.(*AttachRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Player_Detach_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServer).Detach(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipm.Player/Detach",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServer).Detach(ctx, req.(*DetachRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Player_GetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServer).GetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipm.Player/GetMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServer).GetMessage(ctx, req.(*GetMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Player_PutMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServer).PutMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipm.Player/PutMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServer).PutMessage(ctx, req.(*PutMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Player_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ipm.Player",
	HandlerType: (*PlayerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncInfo",
			Handler:    _Player_SyncInfo_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Player_Stop_Handler,
		},
		{
			MethodName: "Attach",
			Handler:    _Player_Attach_Handler,
		},
		{
			MethodName: "Detach",
			Handler:    _Player_Detach_Handler,
		},
		{
			MethodName: "GetMessage",
			Handler:    _Player_GetMessage_Handler,
		},
		{
			MethodName: "PutMessage",
			Handler:    _Player_PutMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pm/pm.proto",
}

func init() { proto.RegisterFile("pm/pm.proto", fileDescriptor_8af9a1f56cafcd39) }

var fileDescriptor_8af9a1f56cafcd39 = []byte{
	// 621 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x6d, 0x93, 0x92, 0x75, 0xb7, 0x74, 0xac, 0x77, 0x68, 0x84, 0x3c, 0x55, 0x06, 0xd6, 0xf1,
	0x92, 0x8a, 0x22, 0xf1, 0x02, 0x02, 0x31, 0x8a, 0xa6, 0x49, 0x54, 0x2b, 0xed, 0x03, 0x12, 0x6f,
	0xde, 0xe6, 0x86, 0x48, 0x4d, 0x62, 0x6a, 0x57, 0x68, 0x7f, 0x80, 0x5f, 0x09, 0xff, 0x05, 0xc5,
	0x8e, 0xf3, 0xd1, 0xae, 0x85, 0x4a, 0x3c, 0xd5, 0xb9, 0xf7, 0xdc, 0xe3, 0x73, 0x6d, 0x9f, 0x5b,
	0x68, 0xf1, 0xa8, 0xcf, 0x23, 0x9f, 0x2f, 0x12, 0x99, 0xa0, 0x1d, 0xf2, 0xc8, 0x3b, 0x12, 0x92,
	0xca, 0xa5, 0xe8, 0xeb, 0x1f, 0x9d, 0xf1, 0x5a, 0x41, 0xd4, 0x0f, 0x32, 0x18, 0xf9, 0x02, 0x47,
	0xe3, 0x39, 0xbd, 0x65, 0x8b, 0x0f, 0x0b, 0x46, 0x25, 0x9b, 0xb0, 0xef, 0x4b, 0x26, 0x24, 0x1e,
	0x82, 0xcd, 0xc3, 0x1b, 0xb7, 0xde, 0xad, 0x9f, 0xee, 0x4f, 0xd2, 0x25, 0x22, 0x34, 0x62, 0x1a,
	0x31, 0xd7, 0x52, 0x21, 0xb5, 0x46, 0x0f, 0x9a, 0x9c, 0x0a, 0xf1, 0x23, 0x59, 0xdc, 0xb8, 0xb6,
	0x8a, 0xe7, 0xdf, 0x24, 0x80, 0x87, 0x55, 0x62, 0xc1, 0x93, 0x58, 0x30, 0x3c, 0x01, 0x47, 0xab,
	0x51, 0xe4, 0xad, 0xc1, 0x81, 0x9f, 0x89, 0x9b, 0xaa, 0x9f, 0x49, 0x96, 0xc5, 0x1e, 0x38, 0x5c,
	0xd5, 0xab, 0x1d, 0x5b, 0x83, 0x07, 0x7e, 0xc8, 0x23, 0x5f, 0x53, 0x5e, 0xc4, 0xb3, 0x64, 0x92,
	0xa5, 0x49, 0xcf, 0x74, 0x30, 0x64, 0x73, 0xb6, 0xa5, 0x03, 0xf2, 0x0c, 0x3a, 0x1a, 0xf8, 0x29,
	0x14, 0x72, 0x33, 0x2c, 0x00, 0x2c, 0xc3, 0x76, 0x94, 0xfd, 0x1c, 0xf6, 0xb4, 0x2e, 0xe1, 0x5a,
	0x5d, 0xfb, 0x2e, 0xdd, 0x26, 0x4f, 0x7e, 0xd6, 0x01, 0x8a, 0x38, 0x1e, 0x80, 0x95, 0x0b, 0xb1,
	0x76, 0x3f, 0xf0, 0x14, 0xcf, 0x24, 0x0d, 0xdc, 0x86, 0xc6, 0xa7, 0xeb, 0x34, 0xc6, 0x93, 0x85,
	0x74, 0xef, 0x75, 0xeb, 0xa7, 0xf6, 0x44, 0xad, 0x4d, 0xc7, 0x8e, 0x0a, 0xa9, 0x8e, 0xf3, 0x37,
	0x30, 0x0d, 0x83, 0xf8, 0x22, 0xfe, 0x7f, 0x6f, 0x60, 0x66, 0xde, 0x80, 0x21, 0xde, 0xf1, 0x30,
	0x8d, 0x7c, 0xab, 0x24, 0xdf, 0xb4, 0x69, 0x17, 0x6d, 0x92, 0x37, 0xe5, 0x7d, 0x2e, 0x97, 0x72,
	0x6b, 0x07, 0xaa, 0xda, 0x2a, 0x55, 0x7f, 0x86, 0xf6, 0x7b, 0x29, 0xe9, 0xf5, 0x37, 0x53, 0x66,
	0x40, 0xf5, 0xd2, 0x49, 0x66, 0x54, 0x56, 0x41, 0xe5, 0x41, 0x33, 0xa0, 0x11, 0x1b, 0xa7, 0x02,
	0xb3, 0xc6, 0xcd, 0x37, 0x79, 0x02, 0xed, 0x21, 0xfb, 0x0b, 0x25, 0xe9, 0x41, 0xe7, 0x9c, 0xc9,
	0x11, 0x13, 0x82, 0x06, 0x6c, 0x1b, 0xf0, 0x0a, 0xb0, 0x0c, 0xdc, 0xf1, 0x10, 0x9f, 0x42, 0x23,
	0x88, 0x44, 0x90, 0xd9, 0xe8, 0xd0, 0x0f, 0x83, 0xc8, 0x3f, 0xa7, 0x11, 0x33, 0x7c, 0x2a, 0x4b,
	0x2e, 0xa1, 0x33, 0x5e, 0xfe, 0x83, 0x18, 0x3c, 0x81, 0x06, 0x2f, 0xe8, 0x50, 0xd1, 0xe9, 0xc3,
	0xcf, 0x09, 0xd3, 0x3c, 0x79, 0x0d, 0x9d, 0xf1, 0x68, 0xc8, 0x66, 0x74, 0x39, 0xdf, 0xd9, 0x45,
	0x83, 0xdf, 0x16, 0x58, 0xe3, 0x11, 0x7e, 0x84, 0xfb, 0xe5, 0x19, 0x82, 0x6e, 0xc9, 0x4b, 0x95,
	0x79, 0xe5, 0x3d, 0xbe, 0x23, 0xa3, 0xf7, 0x24, 0x35, 0x3c, 0x33, 0x34, 0x7a, 0x42, 0x54, 0x68,
	0x2a, 0x43, 0xc3, 0x3b, 0xd6, 0x99, 0x55, 0xdd, 0xa4, 0x86, 0xef, 0x8c, 0x57, 0xd3, 0xa9, 0x80,
	0xc7, 0x25, 0x86, 0xd2, 0x34, 0xf1, 0x1e, 0xad, 0xc5, 0x73, 0x82, 0xbc, 0x17, 0xed, 0x85, 0x8a,
	0x88, 0x8a, 0xef, 0x2a, 0xbd, 0x54, 0x8d, 0x43, 0x6a, 0x38, 0x84, 0x76, 0xe5, 0xa9, 0xe3, 0x2a,
	0xba, 0x78, 0xfe, 0x9b, 0xbb, 0x19, 0xfc, 0xb2, 0xc0, 0xd1, 0x25, 0xe8, 0x43, 0x73, 0x7a, 0x1b,
	0x5f, 0xab, 0x11, 0xb4, 0x3a, 0xab, 0xbc, 0xd5, 0x00, 0xa9, 0xe1, 0x0b, 0x68, 0x4c, 0x65, 0xc2,
	0xd7, 0xb1, 0x9b, 0xcf, 0xee, 0x15, 0x38, 0xda, 0x60, 0x88, 0x0a, 0x53, 0x71, 0xdb, 0xf6, 0x3a,
	0xed, 0xa2, 0xac, 0xae, 0x62, 0xa9, 0xed, 0x77, 0x55, 0xf8, 0x25, 0xbb, 0xab, 0x35, 0xa7, 0x65,
	0x77, 0xb5, 0x6e, 0x2c, 0x52, 0xc3, 0xb7, 0x00, 0x85, 0x19, 0xcc, 0x65, 0xaf, 0xba, 0x63, 0xb3,
	0x80, 0xb3, 0xfd, 0xaf, 0x7b, 0x94, 0x87, 0xfd, 0x90, 0x47, 0x57, 0x8e, 0xfa, 0x9b, 0x7d, 0xf9,
	0x27, 0x00, 0x00, 0xff, 0xff, 0x0d, 0xc0, 0x65, 0x40, 0x9c, 0x07, 0x00, 0x00,
}
