// Code generated by protoc-gen-go. DO NOT EDIT.
// source: debug/debug.proto

package idebug

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	math "math"
	status "status"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StopPprofResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StopPprofResponse) Reset()         { *m = StopPprofResponse{} }
func (m *StopPprofResponse) String() string { return proto.CompactTextString(m) }
func (*StopPprofResponse) ProtoMessage()    {}
func (*StopPprofResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ae24eab94cb53d5, []int{0}
}
func (m *StopPprofResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopPprofResponse.Unmarshal(m, b)
}
func (m *StopPprofResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopPprofResponse.Marshal(b, m, deterministic)
}
func (m *StopPprofResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopPprofResponse.Merge(m, src)
}
func (m *StopPprofResponse) XXX_Size() int {
	return xxx_messageInfo_StopPprofResponse.Size(m)
}
func (m *StopPprofResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopPprofResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopPprofResponse proto.InternalMessageInfo

func (m *StopPprofResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type StartPprofRequest struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartPprofRequest) Reset()         { *m = StartPprofRequest{} }
func (m *StartPprofRequest) String() string { return proto.CompactTextString(m) }
func (*StartPprofRequest) ProtoMessage()    {}
func (*StartPprofRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ae24eab94cb53d5, []int{1}
}
func (m *StartPprofRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartPprofRequest.Unmarshal(m, b)
}
func (m *StartPprofRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartPprofRequest.Marshal(b, m, deterministic)
}
func (m *StartPprofRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartPprofRequest.Merge(m, src)
}
func (m *StartPprofRequest) XXX_Size() int {
	return xxx_messageInfo_StartPprofRequest.Size(m)
}
func (m *StartPprofRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartPprofRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartPprofRequest proto.InternalMessageInfo

func (m *StartPprofRequest) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type StartPprofResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status"`
	Listenaddr           string         `protobuf:"bytes,2,opt,name=listenaddr,proto3" json:"listenaddr"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StartPprofResponse) Reset()         { *m = StartPprofResponse{} }
func (m *StartPprofResponse) String() string { return proto.CompactTextString(m) }
func (*StartPprofResponse) ProtoMessage()    {}
func (*StartPprofResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ae24eab94cb53d5, []int{2}
}
func (m *StartPprofResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartPprofResponse.Unmarshal(m, b)
}
func (m *StartPprofResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartPprofResponse.Marshal(b, m, deterministic)
}
func (m *StartPprofResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartPprofResponse.Merge(m, src)
}
func (m *StartPprofResponse) XXX_Size() int {
	return xxx_messageInfo_StartPprofResponse.Size(m)
}
func (m *StartPprofResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartPprofResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartPprofResponse proto.InternalMessageInfo

func (m *StartPprofResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *StartPprofResponse) GetListenaddr() string {
	if m != nil {
		return m.Listenaddr
	}
	return ""
}

type StatsRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatsRequest) Reset()         { *m = StatsRequest{} }
func (m *StatsRequest) String() string { return proto.CompactTextString(m) }
func (*StatsRequest) ProtoMessage()    {}
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ae24eab94cb53d5, []int{3}
}
func (m *StatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsRequest.Unmarshal(m, b)
}
func (m *StatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsRequest.Marshal(b, m, deterministic)
}
func (m *StatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsRequest.Merge(m, src)
}
func (m *StatsRequest) XXX_Size() int {
	return xxx_messageInfo_StatsRequest.Size(m)
}
func (m *StatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatsRequest proto.InternalMessageInfo

func (m *StatsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StatsResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status"`
	Data                 []byte         `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StatsResponse) Reset()         { *m = StatsResponse{} }
func (m *StatsResponse) String() string { return proto.CompactTextString(m) }
func (*StatsResponse) ProtoMessage()    {}
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ae24eab94cb53d5, []int{4}
}
func (m *StatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsResponse.Unmarshal(m, b)
}
func (m *StatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsResponse.Marshal(b, m, deterministic)
}
func (m *StatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsResponse.Merge(m, src)
}
func (m *StatsResponse) XXX_Size() int {
	return xxx_messageInfo_StatsResponse.Size(m)
}
func (m *StatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatsResponse proto.InternalMessageInfo

func (m *StatsResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *StatsResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type LogRequest struct {
	Level                string   `protobuf:"bytes,1,opt,name=level,proto3" json:"level"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogRequest) Reset()         { *m = LogRequest{} }
func (m *LogRequest) String() string { return proto.CompactTextString(m) }
func (*LogRequest) ProtoMessage()    {}
func (*LogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ae24eab94cb53d5, []int{5}
}
func (m *LogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogRequest.Unmarshal(m, b)
}
func (m *LogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogRequest.Marshal(b, m, deterministic)
}
func (m *LogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogRequest.Merge(m, src)
}
func (m *LogRequest) XXX_Size() int {
	return xxx_messageInfo_LogRequest.Size(m)
}
func (m *LogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogRequest proto.InternalMessageInfo

func (m *LogRequest) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

type LogResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status"`
	Level                string         `protobuf:"bytes,2,opt,name=level,proto3" json:"level"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *LogResponse) Reset()         { *m = LogResponse{} }
func (m *LogResponse) String() string { return proto.CompactTextString(m) }
func (*LogResponse) ProtoMessage()    {}
func (*LogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ae24eab94cb53d5, []int{6}
}
func (m *LogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogResponse.Unmarshal(m, b)
}
func (m *LogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogResponse.Marshal(b, m, deterministic)
}
func (m *LogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogResponse.Merge(m, src)
}
func (m *LogResponse) XXX_Size() int {
	return xxx_messageInfo_LogResponse.Size(m)
}
func (m *LogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogResponse proto.InternalMessageInfo

func (m *LogResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *LogResponse) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

type ProfRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path"`
	Time                 int64    `protobuf:"varint,3,opt,name=time,proto3" json:"time"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfRequest) Reset()         { *m = ProfRequest{} }
func (m *ProfRequest) String() string { return proto.CompactTextString(m) }
func (*ProfRequest) ProtoMessage()    {}
func (*ProfRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ae24eab94cb53d5, []int{7}
}
func (m *ProfRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfRequest.Unmarshal(m, b)
}
func (m *ProfRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfRequest.Marshal(b, m, deterministic)
}
func (m *ProfRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfRequest.Merge(m, src)
}
func (m *ProfRequest) XXX_Size() int {
	return xxx_messageInfo_ProfRequest.Size(m)
}
func (m *ProfRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfRequest proto.InternalMessageInfo

func (m *ProfRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProfRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ProfRequest) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type ProfResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ProfResponse) Reset()         { *m = ProfResponse{} }
func (m *ProfResponse) String() string { return proto.CompactTextString(m) }
func (*ProfResponse) ProtoMessage()    {}
func (*ProfResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ae24eab94cb53d5, []int{8}
}
func (m *ProfResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfResponse.Unmarshal(m, b)
}
func (m *ProfResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfResponse.Marshal(b, m, deterministic)
}
func (m *ProfResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfResponse.Merge(m, src)
}
func (m *ProfResponse) XXX_Size() int {
	return xxx_messageInfo_ProfResponse.Size(m)
}
func (m *ProfResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfResponse proto.InternalMessageInfo

func (m *ProfResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*StopPprofResponse)(nil), "idebug.StopPprofResponse")
	proto.RegisterType((*StartPprofRequest)(nil), "idebug.StartPprofRequest")
	proto.RegisterType((*StartPprofResponse)(nil), "idebug.StartPprofResponse")
	proto.RegisterType((*StatsRequest)(nil), "idebug.StatsRequest")
	proto.RegisterType((*StatsResponse)(nil), "idebug.StatsResponse")
	proto.RegisterType((*LogRequest)(nil), "idebug.LogRequest")
	proto.RegisterType((*LogResponse)(nil), "idebug.LogResponse")
	proto.RegisterType((*ProfRequest)(nil), "idebug.ProfRequest")
	proto.RegisterType((*ProfResponse)(nil), "idebug.ProfResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DebugClient is the client API for Debug service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DebugClient interface {
	Prof(ctx context.Context, in *ProfRequest, opts ...grpc.CallOption) (*ProfResponse, error)
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	GetLogLevel(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*LogResponse, error)
	SetLogLevel(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
	StartPprof(ctx context.Context, in *StartPprofRequest, opts ...grpc.CallOption) (*StartPprofResponse, error)
	StopPprof(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StopPprofResponse, error)
}

type debugClient struct {
	cc *grpc.ClientConn
}

func NewDebugClient(cc *grpc.ClientConn) DebugClient {
	return &debugClient{cc}
}

func (c *debugClient) Prof(ctx context.Context, in *ProfRequest, opts ...grpc.CallOption) (*ProfResponse, error) {
	out := new(ProfResponse)
	err := c.cc.Invoke(ctx, "/idebug.Debug/Prof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, "/idebug.Debug/Stats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugClient) GetLogLevel(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*LogResponse, error) {
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, "/idebug.Debug/GetLogLevel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugClient) SetLogLevel(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, "/idebug.Debug/SetLogLevel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugClient) StartPprof(ctx context.Context, in *StartPprofRequest, opts ...grpc.CallOption) (*StartPprofResponse, error) {
	out := new(StartPprofResponse)
	err := c.cc.Invoke(ctx, "/idebug.Debug/StartPprof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugClient) StopPprof(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StopPprofResponse, error) {
	out := new(StopPprofResponse)
	err := c.cc.Invoke(ctx, "/idebug.Debug/StopPprof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DebugServer is the server API for Debug service.
type DebugServer interface {
	Prof(context.Context, *ProfRequest) (*ProfResponse, error)
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	GetLogLevel(context.Context, *empty.Empty) (*LogResponse, error)
	SetLogLevel(context.Context, *LogRequest) (*LogResponse, error)
	StartPprof(context.Context, *StartPprofRequest) (*StartPprofResponse, error)
	StopPprof(context.Context, *empty.Empty) (*StopPprofResponse, error)
}

func RegisterDebugServer(s *grpc.Server, srv DebugServer) {
	s.RegisterService(&_Debug_serviceDesc, srv)
}

func _Debug_Prof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServer).Prof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idebug.Debug/Prof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServer).Prof(ctx, req.(*ProfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Debug_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idebug.Debug/Stats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Debug_GetLogLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServer).GetLogLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idebug.Debug/GetLogLevel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServer).GetLogLevel(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Debug_SetLogLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServer).SetLogLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idebug.Debug/SetLogLevel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServer).SetLogLevel(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Debug_StartPprof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartPprofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServer).StartPprof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idebug.Debug/StartPprof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServer).StartPprof(ctx, req.(*StartPprofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Debug_StopPprof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServer).StopPprof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idebug.Debug/StopPprof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServer).StopPprof(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Debug_serviceDesc = grpc.ServiceDesc{
	ServiceName: "idebug.Debug",
	HandlerType: (*DebugServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prof",
			Handler:    _Debug_Prof_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _Debug_Stats_Handler,
		},
		{
			MethodName: "GetLogLevel",
			Handler:    _Debug_GetLogLevel_Handler,
		},
		{
			MethodName: "SetLogLevel",
			Handler:    _Debug_SetLogLevel_Handler,
		},
		{
			MethodName: "StartPprof",
			Handler:    _Debug_StartPprof_Handler,
		},
		{
			MethodName: "StopPprof",
			Handler:    _Debug_StopPprof_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "debug/debug.proto",
}

func init() { proto.RegisterFile("debug/debug.proto", fileDescriptor_5ae24eab94cb53d5) }

var fileDescriptor_5ae24eab94cb53d5 = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xcf, 0x6b, 0xe2, 0x40,
	0x14, 0xf6, 0x37, 0xf8, 0x92, 0x5d, 0x70, 0x74, 0x17, 0x37, 0x0b, 0x8b, 0xcc, 0x61, 0xeb, 0x29,
	0x01, 0x05, 0x29, 0xb4, 0x87, 0x52, 0x2a, 0xa5, 0xe8, 0x41, 0xe2, 0xad, 0xf4, 0x32, 0x92, 0x31,
	0x0d, 0x44, 0x27, 0x4d, 0x26, 0x85, 0xfe, 0xe1, 0xbd, 0x97, 0x79, 0x13, 0xd3, 0x89, 0xd4, 0x83,
	0xbd, 0x98, 0x37, 0xef, 0xbd, 0xef, 0xfb, 0x9e, 0x6f, 0xbe, 0x81, 0x5e, 0xc0, 0x37, 0x79, 0xe8,
	0xe1, 0xaf, 0x9b, 0xa4, 0x42, 0x0a, 0xd2, 0x89, 0xf0, 0xe4, 0xf4, 0x33, 0xc9, 0x64, 0x9e, 0x79,
	0xfa, 0xa3, 0x8b, 0xce, 0xdf, 0x50, 0x88, 0x30, 0xe6, 0x1e, 0x9e, 0x36, 0xf9, 0xd6, 0xe3, 0xbb,
	0x44, 0xbe, 0xe9, 0x22, 0xbd, 0x82, 0xde, 0x5a, 0x8a, 0x64, 0x95, 0xa4, 0x62, 0xeb, 0xf3, 0x2c,
	0x11, 0xfb, 0x8c, 0x93, 0xff, 0xd0, 0xd1, 0x0c, 0xc3, 0xfa, 0xa8, 0x3e, 0xb6, 0x26, 0x3f, 0xdd,
	0x82, 0x70, 0x8d, 0x1f, 0xbf, 0xa8, 0xd2, 0x0b, 0x05, 0x66, 0xa9, 0x2c, 0xd0, 0x2f, 0x39, 0xcf,
	0x24, 0x21, 0xd0, 0x62, 0x41, 0x90, 0x22, 0xb4, 0xeb, 0x63, 0x4c, 0x9f, 0x80, 0x98, 0x8d, 0xe7,
	0xc9, 0x90, 0x7f, 0x00, 0x71, 0x94, 0x49, 0xbe, 0x47, 0xde, 0x06, 0xf2, 0x1a, 0x19, 0x4a, 0xc1,
	0x56, 0x88, 0xcc, 0x98, 0x60, 0xcf, 0x76, 0xfc, 0x30, 0x81, 0x8a, 0xe9, 0x02, 0x7e, 0x14, 0x3d,
	0x67, 0x8a, 0x13, 0x68, 0x05, 0x4c, 0x32, 0x94, 0xb5, 0x7d, 0x8c, 0x29, 0x05, 0x58, 0x8a, 0xf0,
	0x20, 0x37, 0x80, 0x76, 0xcc, 0x5f, 0x79, 0x5c, 0xe8, 0xe9, 0x03, 0x5d, 0x80, 0x85, 0x3d, 0x67,
	0xca, 0x95, 0x64, 0x0d, 0x93, 0xec, 0x01, 0xac, 0x55, 0x75, 0xc5, 0xc7, 0x7f, 0x50, 0xe5, 0x12,
	0x26, 0x9f, 0x0b, 0x1c, 0xc6, 0x2a, 0x27, 0xa3, 0x1d, 0x1f, 0x36, 0x47, 0xf5, 0x71, 0xd3, 0xc7,
	0x98, 0xce, 0xc0, 0x5e, 0x7d, 0xe3, 0x12, 0x26, 0xef, 0x0d, 0x68, 0xdf, 0x29, 0x93, 0x91, 0x29,
	0xb4, 0x14, 0x03, 0xe9, 0xbb, 0xda, 0x75, 0xae, 0x31, 0x9a, 0x33, 0xa8, 0x26, 0xb5, 0x08, 0xad,
	0x91, 0x19, 0xb4, 0x71, 0xff, 0xa4, 0x6c, 0x30, 0xaf, 0xcc, 0xf9, 0x75, 0x94, 0x2d, 0x71, 0xd7,
	0x60, 0xdd, 0x73, 0xb9, 0x14, 0xe1, 0x52, 0x2d, 0x82, 0xfc, 0x76, 0xb5, 0x99, 0xdd, 0x83, 0x99,
	0xdd, 0xb9, 0x32, 0xb3, 0x53, 0xce, 0x62, 0xec, 0x9c, 0xd6, 0xc8, 0x25, 0x58, 0x6b, 0x03, 0x4d,
	0x2a, 0x5d, 0x5a, 0xf9, 0x04, 0x72, 0x0e, 0xf0, 0xe9, 0x58, 0xf2, 0xc7, 0x18, 0xaf, 0x6a, 0x77,
	0xc7, 0xf9, 0xaa, 0x54, 0xd2, 0xdc, 0x40, 0xb7, 0x7c, 0x5e, 0x27, 0x87, 0x37, 0xd8, 0x8f, 0x5e,
	0x22, 0xad, 0xdd, 0xda, 0x8f, 0xc0, 0x92, 0xc8, 0xd3, 0x1d, 0x9b, 0x0e, 0x42, 0xa7, 0x1f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xd2, 0x62, 0x5b, 0x0d, 0x04, 0x04, 0x00, 0x00,
}
