// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gm/gm.proto

package igm

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	status "status"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GameUpRequest struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameUpRequest) Reset()         { *m = GameUpRequest{} }
func (m *GameUpRequest) String() string { return proto.CompactTextString(m) }
func (*GameUpRequest) ProtoMessage()    {}
func (*GameUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_910b291f729993e2, []int{0}
}
func (m *GameUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameUpRequest.Unmarshal(m, b)
}
func (m *GameUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameUpRequest.Marshal(b, m, deterministic)
}
func (m *GameUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameUpRequest.Merge(m, src)
}
func (m *GameUpRequest) XXX_Size() int {
	return xxx_messageInfo_GameUpRequest.Size(m)
}
func (m *GameUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GameUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GameUpRequest proto.InternalMessageInfo

func (m *GameUpRequest) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

type GameCreateRequest struct {
	GameType             int64    `protobuf:"varint,1,opt,name=gameType,proto3" json:"gameType"`
	Port                 int64    `protobuf:"varint,2,opt,name=port,proto3" json:"port"`
	Gid                  string   `protobuf:"bytes,3,opt,name=gid,proto3" json:"gid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameCreateRequest) Reset()         { *m = GameCreateRequest{} }
func (m *GameCreateRequest) String() string { return proto.CompactTextString(m) }
func (*GameCreateRequest) ProtoMessage()    {}
func (*GameCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_910b291f729993e2, []int{1}
}
func (m *GameCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameCreateRequest.Unmarshal(m, b)
}
func (m *GameCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameCreateRequest.Marshal(b, m, deterministic)
}
func (m *GameCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameCreateRequest.Merge(m, src)
}
func (m *GameCreateRequest) XXX_Size() int {
	return xxx_messageInfo_GameCreateRequest.Size(m)
}
func (m *GameCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GameCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GameCreateRequest proto.InternalMessageInfo

func (m *GameCreateRequest) GetGameType() int64 {
	if m != nil {
		return m.GameType
	}
	return 0
}

func (m *GameCreateRequest) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *GameCreateRequest) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

type GameCreateResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status"`
	GameType             int64          `protobuf:"varint,2,opt,name=gameType,proto3" json:"gameType"`
	Gid                  string         `protobuf:"bytes,3,opt,name=gid,proto3" json:"gid"`
	Port                 int64          `protobuf:"varint,4,opt,name=port,proto3" json:"port"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GameCreateResponse) Reset()         { *m = GameCreateResponse{} }
func (m *GameCreateResponse) String() string { return proto.CompactTextString(m) }
func (*GameCreateResponse) ProtoMessage()    {}
func (*GameCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_910b291f729993e2, []int{2}
}
func (m *GameCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameCreateResponse.Unmarshal(m, b)
}
func (m *GameCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameCreateResponse.Marshal(b, m, deterministic)
}
func (m *GameCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameCreateResponse.Merge(m, src)
}
func (m *GameCreateResponse) XXX_Size() int {
	return xxx_messageInfo_GameCreateResponse.Size(m)
}
func (m *GameCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GameCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GameCreateResponse proto.InternalMessageInfo

func (m *GameCreateResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GameCreateResponse) GetGameType() int64 {
	if m != nil {
		return m.GameType
	}
	return 0
}

func (m *GameCreateResponse) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *GameCreateResponse) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

type GameDeleteRequest struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameDeleteRequest) Reset()         { *m = GameDeleteRequest{} }
func (m *GameDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*GameDeleteRequest) ProtoMessage()    {}
func (*GameDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_910b291f729993e2, []int{3}
}
func (m *GameDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameDeleteRequest.Unmarshal(m, b)
}
func (m *GameDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameDeleteRequest.Marshal(b, m, deterministic)
}
func (m *GameDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameDeleteRequest.Merge(m, src)
}
func (m *GameDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_GameDeleteRequest.Size(m)
}
func (m *GameDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GameDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GameDeleteRequest proto.InternalMessageInfo

func (m *GameDeleteRequest) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

type GameListRequest struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameListRequest) Reset()         { *m = GameListRequest{} }
func (m *GameListRequest) String() string { return proto.CompactTextString(m) }
func (*GameListRequest) ProtoMessage()    {}
func (*GameListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_910b291f729993e2, []int{4}
}
func (m *GameListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameListRequest.Unmarshal(m, b)
}
func (m *GameListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameListRequest.Marshal(b, m, deterministic)
}
func (m *GameListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameListRequest.Merge(m, src)
}
func (m *GameListRequest) XXX_Size() int {
	return xxx_messageInfo_GameListRequest.Size(m)
}
func (m *GameListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GameListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GameListRequest proto.InternalMessageInfo

func (m *GameListRequest) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

type GameListResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status"`
	Games                []*GameInfo    `protobuf:"bytes,2,rep,name=games,proto3" json:"games"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GameListResponse) Reset()         { *m = GameListResponse{} }
func (m *GameListResponse) String() string { return proto.CompactTextString(m) }
func (*GameListResponse) ProtoMessage()    {}
func (*GameListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_910b291f729993e2, []int{5}
}
func (m *GameListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameListResponse.Unmarshal(m, b)
}
func (m *GameListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameListResponse.Marshal(b, m, deterministic)
}
func (m *GameListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameListResponse.Merge(m, src)
}
func (m *GameListResponse) XXX_Size() int {
	return xxx_messageInfo_GameListResponse.Size(m)
}
func (m *GameListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GameListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GameListResponse proto.InternalMessageInfo

func (m *GameListResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GameListResponse) GetGames() []*GameInfo {
	if m != nil {
		return m.Games
	}
	return nil
}

type GameInfo struct {
	Gid                  string            `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid"`
	State                int64             `protobuf:"varint,2,opt,name=state,proto3" json:"state"`
	GameType             int64             `protobuf:"varint,3,opt,name=gameType,proto3" json:"gameType"`
	Port                 int64             `protobuf:"varint,4,opt,name=port,proto3" json:"port"`
	Pid                  int64             `protobuf:"varint,5,opt,name=pid,proto3" json:"pid"`
	Players              map[string]string `protobuf:"bytes,6,rep,name=players,proto3" json:"players" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GameInfo) Reset()         { *m = GameInfo{} }
func (m *GameInfo) String() string { return proto.CompactTextString(m) }
func (*GameInfo) ProtoMessage()    {}
func (*GameInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_910b291f729993e2, []int{6}
}
func (m *GameInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameInfo.Unmarshal(m, b)
}
func (m *GameInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameInfo.Marshal(b, m, deterministic)
}
func (m *GameInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameInfo.Merge(m, src)
}
func (m *GameInfo) XXX_Size() int {
	return xxx_messageInfo_GameInfo.Size(m)
}
func (m *GameInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GameInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GameInfo proto.InternalMessageInfo

func (m *GameInfo) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *GameInfo) GetState() int64 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *GameInfo) GetGameType() int64 {
	if m != nil {
		return m.GameType
	}
	return 0
}

func (m *GameInfo) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *GameInfo) GetPid() int64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *GameInfo) GetPlayers() map[string]string {
	if m != nil {
		return m.Players
	}
	return nil
}

type GameStartRequest struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid"`
	Pid                  string   `protobuf:"bytes,2,opt,name=pid,proto3" json:"pid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameStartRequest) Reset()         { *m = GameStartRequest{} }
func (m *GameStartRequest) String() string { return proto.CompactTextString(m) }
func (*GameStartRequest) ProtoMessage()    {}
func (*GameStartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_910b291f729993e2, []int{7}
}
func (m *GameStartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameStartRequest.Unmarshal(m, b)
}
func (m *GameStartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameStartRequest.Marshal(b, m, deterministic)
}
func (m *GameStartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameStartRequest.Merge(m, src)
}
func (m *GameStartRequest) XXX_Size() int {
	return xxx_messageInfo_GameStartRequest.Size(m)
}
func (m *GameStartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GameStartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GameStartRequest proto.InternalMessageInfo

func (m *GameStartRequest) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *GameStartRequest) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

type GameStopRequest struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid"`
	Pid                  string   `protobuf:"bytes,2,opt,name=pid,proto3" json:"pid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameStopRequest) Reset()         { *m = GameStopRequest{} }
func (m *GameStopRequest) String() string { return proto.CompactTextString(m) }
func (*GameStopRequest) ProtoMessage()    {}
func (*GameStopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_910b291f729993e2, []int{8}
}
func (m *GameStopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameStopRequest.Unmarshal(m, b)
}
func (m *GameStopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameStopRequest.Marshal(b, m, deterministic)
}
func (m *GameStopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameStopRequest.Merge(m, src)
}
func (m *GameStopRequest) XXX_Size() int {
	return xxx_messageInfo_GameStopRequest.Size(m)
}
func (m *GameStopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GameStopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GameStopRequest proto.InternalMessageInfo

func (m *GameStopRequest) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *GameStopRequest) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

type GMDefaultResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GMDefaultResponse) Reset()         { *m = GMDefaultResponse{} }
func (m *GMDefaultResponse) String() string { return proto.CompactTextString(m) }
func (*GMDefaultResponse) ProtoMessage()    {}
func (*GMDefaultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_910b291f729993e2, []int{9}
}
func (m *GMDefaultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GMDefaultResponse.Unmarshal(m, b)
}
func (m *GMDefaultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GMDefaultResponse.Marshal(b, m, deterministic)
}
func (m *GMDefaultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GMDefaultResponse.Merge(m, src)
}
func (m *GMDefaultResponse) XXX_Size() int {
	return xxx_messageInfo_GMDefaultResponse.Size(m)
}
func (m *GMDefaultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GMDefaultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GMDefaultResponse proto.InternalMessageInfo

func (m *GMDefaultResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type GameExitRequest struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid"`
	Pid                  string   `protobuf:"bytes,2,opt,name=pid,proto3" json:"pid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameExitRequest) Reset()         { *m = GameExitRequest{} }
func (m *GameExitRequest) String() string { return proto.CompactTextString(m) }
func (*GameExitRequest) ProtoMessage()    {}
func (*GameExitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_910b291f729993e2, []int{10}
}
func (m *GameExitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameExitRequest.Unmarshal(m, b)
}
func (m *GameExitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameExitRequest.Marshal(b, m, deterministic)
}
func (m *GameExitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameExitRequest.Merge(m, src)
}
func (m *GameExitRequest) XXX_Size() int {
	return xxx_messageInfo_GameExitRequest.Size(m)
}
func (m *GameExitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GameExitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GameExitRequest proto.InternalMessageInfo

func (m *GameExitRequest) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *GameExitRequest) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

type AddPlayerRequest struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid"`
	Pid                  string   `protobuf:"bytes,2,opt,name=pid,proto3" json:"pid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPlayerRequest) Reset()         { *m = AddPlayerRequest{} }
func (m *AddPlayerRequest) String() string { return proto.CompactTextString(m) }
func (*AddPlayerRequest) ProtoMessage()    {}
func (*AddPlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_910b291f729993e2, []int{11}
}
func (m *AddPlayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPlayerRequest.Unmarshal(m, b)
}
func (m *AddPlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPlayerRequest.Marshal(b, m, deterministic)
}
func (m *AddPlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPlayerRequest.Merge(m, src)
}
func (m *AddPlayerRequest) XXX_Size() int {
	return xxx_messageInfo_AddPlayerRequest.Size(m)
}
func (m *AddPlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPlayerRequest proto.InternalMessageInfo

func (m *AddPlayerRequest) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *AddPlayerRequest) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

type DelPlayerRequest struct {
	Gid                  string   `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid"`
	Pid                  string   `protobuf:"bytes,2,opt,name=pid,proto3" json:"pid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelPlayerRequest) Reset()         { *m = DelPlayerRequest{} }
func (m *DelPlayerRequest) String() string { return proto.CompactTextString(m) }
func (*DelPlayerRequest) ProtoMessage()    {}
func (*DelPlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_910b291f729993e2, []int{12}
}
func (m *DelPlayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelPlayerRequest.Unmarshal(m, b)
}
func (m *DelPlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelPlayerRequest.Marshal(b, m, deterministic)
}
func (m *DelPlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelPlayerRequest.Merge(m, src)
}
func (m *DelPlayerRequest) XXX_Size() int {
	return xxx_messageInfo_DelPlayerRequest.Size(m)
}
func (m *DelPlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelPlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelPlayerRequest proto.InternalMessageInfo

func (m *DelPlayerRequest) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *DelPlayerRequest) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

type AddPlayerResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status"`
	GameAddr             string         `protobuf:"bytes,2,opt,name=gameAddr,proto3" json:"gameAddr"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddPlayerResponse) Reset()         { *m = AddPlayerResponse{} }
func (m *AddPlayerResponse) String() string { return proto.CompactTextString(m) }
func (*AddPlayerResponse) ProtoMessage()    {}
func (*AddPlayerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_910b291f729993e2, []int{13}
}
func (m *AddPlayerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPlayerResponse.Unmarshal(m, b)
}
func (m *AddPlayerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPlayerResponse.Marshal(b, m, deterministic)
}
func (m *AddPlayerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPlayerResponse.Merge(m, src)
}
func (m *AddPlayerResponse) XXX_Size() int {
	return xxx_messageInfo_AddPlayerResponse.Size(m)
}
func (m *AddPlayerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPlayerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddPlayerResponse proto.InternalMessageInfo

func (m *AddPlayerResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *AddPlayerResponse) GetGameAddr() string {
	if m != nil {
		return m.GameAddr
	}
	return ""
}

type GameMessage struct {
	MsgType              int64    `protobuf:"varint,1,opt,name=msgType,proto3" json:"msgType"`
	YourCards            []int64  `protobuf:"varint,2,rep,packed,name=yourCards,proto3" json:"yourCards"`
	LastCards            []int64  `protobuf:"varint,3,rep,packed,name=lastCards,proto3" json:"lastCards"`
	LastId               string   `protobuf:"bytes,4,opt,name=lastId,proto3" json:"lastId"`
	RoundOwner           string   `protobuf:"bytes,5,opt,name=roundOwner,proto3" json:"roundOwner"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameMessage) Reset()         { *m = GameMessage{} }
func (m *GameMessage) String() string { return proto.CompactTextString(m) }
func (*GameMessage) ProtoMessage()    {}
func (*GameMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_910b291f729993e2, []int{14}
}
func (m *GameMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameMessage.Unmarshal(m, b)
}
func (m *GameMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameMessage.Marshal(b, m, deterministic)
}
func (m *GameMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameMessage.Merge(m, src)
}
func (m *GameMessage) XXX_Size() int {
	return xxx_messageInfo_GameMessage.Size(m)
}
func (m *GameMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GameMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GameMessage proto.InternalMessageInfo

func (m *GameMessage) GetMsgType() int64 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *GameMessage) GetYourCards() []int64 {
	if m != nil {
		return m.YourCards
	}
	return nil
}

func (m *GameMessage) GetLastCards() []int64 {
	if m != nil {
		return m.LastCards
	}
	return nil
}

func (m *GameMessage) GetLastId() string {
	if m != nil {
		return m.LastId
	}
	return ""
}

func (m *GameMessage) GetRoundOwner() string {
	if m != nil {
		return m.RoundOwner
	}
	return ""
}

type PlayerMessage struct {
	MsgType              int64    `protobuf:"varint,1,opt,name=msgType,proto3" json:"msgType"`
	PutCards             []int64  `protobuf:"varint,2,rep,packed,name=putCards,proto3" json:"putCards"`
	Pid                  string   `protobuf:"bytes,3,opt,name=pid,proto3" json:"pid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerMessage) Reset()         { *m = PlayerMessage{} }
func (m *PlayerMessage) String() string { return proto.CompactTextString(m) }
func (*PlayerMessage) ProtoMessage()    {}
func (*PlayerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_910b291f729993e2, []int{15}
}
func (m *PlayerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerMessage.Unmarshal(m, b)
}
func (m *PlayerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerMessage.Marshal(b, m, deterministic)
}
func (m *PlayerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerMessage.Merge(m, src)
}
func (m *PlayerMessage) XXX_Size() int {
	return xxx_messageInfo_PlayerMessage.Size(m)
}
func (m *PlayerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerMessage proto.InternalMessageInfo

func (m *PlayerMessage) GetMsgType() int64 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *PlayerMessage) GetPutCards() []int64 {
	if m != nil {
		return m.PutCards
	}
	return nil
}

func (m *PlayerMessage) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func init() {
	proto.RegisterType((*GameUpRequest)(nil), "igm.GameUpRequest")
	proto.RegisterType((*GameCreateRequest)(nil), "igm.GameCreateRequest")
	proto.RegisterType((*GameCreateResponse)(nil), "igm.GameCreateResponse")
	proto.RegisterType((*GameDeleteRequest)(nil), "igm.GameDeleteRequest")
	proto.RegisterType((*GameListRequest)(nil), "igm.GameListRequest")
	proto.RegisterType((*GameListResponse)(nil), "igm.GameListResponse")
	proto.RegisterType((*GameInfo)(nil), "igm.GameInfo")
	proto.RegisterMapType((map[string]string)(nil), "igm.GameInfo.PlayersEntry")
	proto.RegisterType((*GameStartRequest)(nil), "igm.GameStartRequest")
	proto.RegisterType((*GameStopRequest)(nil), "igm.GameStopRequest")
	proto.RegisterType((*GMDefaultResponse)(nil), "igm.GMDefaultResponse")
	proto.RegisterType((*GameExitRequest)(nil), "igm.GameExitRequest")
	proto.RegisterType((*AddPlayerRequest)(nil), "igm.AddPlayerRequest")
	proto.RegisterType((*DelPlayerRequest)(nil), "igm.DelPlayerRequest")
	proto.RegisterType((*AddPlayerResponse)(nil), "igm.AddPlayerResponse")
	proto.RegisterType((*GameMessage)(nil), "igm.GameMessage")
	proto.RegisterType((*PlayerMessage)(nil), "igm.PlayerMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GMClient is the client API for GM service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GMClient interface {
	GameCreate(ctx context.Context, in *GameCreateRequest, opts ...grpc.CallOption) (*GameCreateResponse, error)
	GameDelete(ctx context.Context, in *GameDeleteRequest, opts ...grpc.CallOption) (*GMDefaultResponse, error)
	GameList(ctx context.Context, in *GameListRequest, opts ...grpc.CallOption) (*GameListResponse, error)
	GameStart(ctx context.Context, in *GameStartRequest, opts ...grpc.CallOption) (*GMDefaultResponse, error)
	GameStop(ctx context.Context, in *GameStopRequest, opts ...grpc.CallOption) (*GMDefaultResponse, error)
	GameAddPlayer(ctx context.Context, in *AddPlayerRequest, opts ...grpc.CallOption) (*AddPlayerResponse, error)
	GameDelPlayer(ctx context.Context, in *DelPlayerRequest, opts ...grpc.CallOption) (*GMDefaultResponse, error)
	GameUp(ctx context.Context, in *GameUpRequest, opts ...grpc.CallOption) (*GMDefaultResponse, error)
	GameExit(ctx context.Context, in *GameExitRequest, opts ...grpc.CallOption) (*GMDefaultResponse, error)
}

type gMClient struct {
	cc *grpc.ClientConn
}

func NewGMClient(cc *grpc.ClientConn) GMClient {
	return &gMClient{cc}
}

func (c *gMClient) GameCreate(ctx context.Context, in *GameCreateRequest, opts ...grpc.CallOption) (*GameCreateResponse, error) {
	out := new(GameCreateResponse)
	err := c.cc.Invoke(ctx, "/igm.GM/GameCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gMClient) GameDelete(ctx context.Context, in *GameDeleteRequest, opts ...grpc.CallOption) (*GMDefaultResponse, error) {
	out := new(GMDefaultResponse)
	err := c.cc.Invoke(ctx, "/igm.GM/GameDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gMClient) GameList(ctx context.Context, in *GameListRequest, opts ...grpc.CallOption) (*GameListResponse, error) {
	out := new(GameListResponse)
	err := c.cc.Invoke(ctx, "/igm.GM/GameList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gMClient) GameStart(ctx context.Context, in *GameStartRequest, opts ...grpc.CallOption) (*GMDefaultResponse, error) {
	out := new(GMDefaultResponse)
	err := c.cc.Invoke(ctx, "/igm.GM/GameStart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gMClient) GameStop(ctx context.Context, in *GameStopRequest, opts ...grpc.CallOption) (*GMDefaultResponse, error) {
	out := new(GMDefaultResponse)
	err := c.cc.Invoke(ctx, "/igm.GM/GameStop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gMClient) GameAddPlayer(ctx context.Context, in *AddPlayerRequest, opts ...grpc.CallOption) (*AddPlayerResponse, error) {
	out := new(AddPlayerResponse)
	err := c.cc.Invoke(ctx, "/igm.GM/GameAddPlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gMClient) GameDelPlayer(ctx context.Context, in *DelPlayerRequest, opts ...grpc.CallOption) (*GMDefaultResponse, error) {
	out := new(GMDefaultResponse)
	err := c.cc.Invoke(ctx, "/igm.GM/GameDelPlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gMClient) GameUp(ctx context.Context, in *GameUpRequest, opts ...grpc.CallOption) (*GMDefaultResponse, error) {
	out := new(GMDefaultResponse)
	err := c.cc.Invoke(ctx, "/igm.GM/GameUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gMClient) GameExit(ctx context.Context, in *GameExitRequest, opts ...grpc.CallOption) (*GMDefaultResponse, error) {
	out := new(GMDefaultResponse)
	err := c.cc.Invoke(ctx, "/igm.GM/GameExit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GMServer is the server API for GM service.
type GMServer interface {
	GameCreate(context.Context, *GameCreateRequest) (*GameCreateResponse, error)
	GameDelete(context.Context, *GameDeleteRequest) (*GMDefaultResponse, error)
	GameList(context.Context, *GameListRequest) (*GameListResponse, error)
	GameStart(context.Context, *GameStartRequest) (*GMDefaultResponse, error)
	GameStop(context.Context, *GameStopRequest) (*GMDefaultResponse, error)
	GameAddPlayer(context.Context, *AddPlayerRequest) (*AddPlayerResponse, error)
	GameDelPlayer(context.Context, *DelPlayerRequest) (*GMDefaultResponse, error)
	GameUp(context.Context, *GameUpRequest) (*GMDefaultResponse, error)
	GameExit(context.Context, *GameExitRequest) (*GMDefaultResponse, error)
}

func RegisterGMServer(s *grpc.Server, srv GMServer) {
	s.RegisterService(&_GM_serviceDesc, srv)
}

func _GM_GameCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GMServer).GameCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/igm.GM/GameCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GMServer).GameCreate(ctx, req.(*GameCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GM_GameDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GMServer).GameDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/igm.GM/GameDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GMServer).GameDelete(ctx, req.(*GameDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GM_GameList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GMServer).GameList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/igm.GM/GameList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GMServer).GameList(ctx, req.(*GameListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GM_GameStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GMServer).GameStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/igm.GM/GameStart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GMServer).GameStart(ctx, req.(*GameStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GM_GameStop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GMServer).GameStop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/igm.GM/GameStop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GMServer).GameStop(ctx, req.(*GameStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GM_GameAddPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GMServer).GameAddPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/igm.GM/GameAddPlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GMServer).GameAddPlayer(ctx, req.(*AddPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GM_GameDelPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GMServer).GameDelPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/igm.GM/GameDelPlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GMServer).GameDelPlayer(ctx, req.(*DelPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GM_GameUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GMServer).GameUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/igm.GM/GameUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GMServer).GameUp(ctx, req.(*GameUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GM_GameExit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameExitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GMServer).GameExit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/igm.GM/GameExit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GMServer).GameExit(ctx, req.(*GameExitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GM_serviceDesc = grpc.ServiceDesc{
	ServiceName: "igm.GM",
	HandlerType: (*GMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GameCreate",
			Handler:    _GM_GameCreate_Handler,
		},
		{
			MethodName: "GameDelete",
			Handler:    _GM_GameDelete_Handler,
		},
		{
			MethodName: "GameList",
			Handler:    _GM_GameList_Handler,
		},
		{
			MethodName: "GameStart",
			Handler:    _GM_GameStart_Handler,
		},
		{
			MethodName: "GameStop",
			Handler:    _GM_GameStop_Handler,
		},
		{
			MethodName: "GameAddPlayer",
			Handler:    _GM_GameAddPlayer_Handler,
		},
		{
			MethodName: "GameDelPlayer",
			Handler:    _GM_GameDelPlayer_Handler,
		},
		{
			MethodName: "GameUp",
			Handler:    _GM_GameUp_Handler,
		},
		{
			MethodName: "GameExit",
			Handler:    _GM_GameExit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gm/gm.proto",
}

// GameClient is the client API for Game service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GameClient interface {
	AddPlayer(ctx context.Context, in *AddPlayerRequest, opts ...grpc.CallOption) (*GMDefaultResponse, error)
	DelPlayer(ctx context.Context, in *DelPlayerRequest, opts ...grpc.CallOption) (*GMDefaultResponse, error)
	PlayerConn(ctx context.Context, opts ...grpc.CallOption) (Game_PlayerConnClient, error)
	Start(ctx context.Context, in *GameStartRequest, opts ...grpc.CallOption) (*GMDefaultResponse, error)
	Stop(ctx context.Context, in *GameStopRequest, opts ...grpc.CallOption) (*GMDefaultResponse, error)
	Exit(ctx context.Context, in *GameExitRequest, opts ...grpc.CallOption) (*GMDefaultResponse, error)
}

type gameClient struct {
	cc *grpc.ClientConn
}

func NewGameClient(cc *grpc.ClientConn) GameClient {
	return &gameClient{cc}
}

func (c *gameClient) AddPlayer(ctx context.Context, in *AddPlayerRequest, opts ...grpc.CallOption) (*GMDefaultResponse, error) {
	out := new(GMDefaultResponse)
	err := c.cc.Invoke(ctx, "/igm.Game/AddPlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) DelPlayer(ctx context.Context, in *DelPlayerRequest, opts ...grpc.CallOption) (*GMDefaultResponse, error) {
	out := new(GMDefaultResponse)
	err := c.cc.Invoke(ctx, "/igm.Game/DelPlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) PlayerConn(ctx context.Context, opts ...grpc.CallOption) (Game_PlayerConnClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Game_serviceDesc.Streams[0], "/igm.Game/PlayerConn", opts...)
	if err != nil {
		return nil, err
	}
	x := &gamePlayerConnClient{stream}
	return x, nil
}

type Game_PlayerConnClient interface {
	Send(*PlayerMessage) error
	Recv() (*GameMessage, error)
	grpc.ClientStream
}

type gamePlayerConnClient struct {
	grpc.ClientStream
}

func (x *gamePlayerConnClient) Send(m *PlayerMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gamePlayerConnClient) Recv() (*GameMessage, error) {
	m := new(GameMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gameClient) Start(ctx context.Context, in *GameStartRequest, opts ...grpc.CallOption) (*GMDefaultResponse, error) {
	out := new(GMDefaultResponse)
	err := c.cc.Invoke(ctx, "/igm.Game/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) Stop(ctx context.Context, in *GameStopRequest, opts ...grpc.CallOption) (*GMDefaultResponse, error) {
	out := new(GMDefaultResponse)
	err := c.cc.Invoke(ctx, "/igm.Game/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) Exit(ctx context.Context, in *GameExitRequest, opts ...grpc.CallOption) (*GMDefaultResponse, error) {
	out := new(GMDefaultResponse)
	err := c.cc.Invoke(ctx, "/igm.Game/Exit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServer is the server API for Game service.
type GameServer interface {
	AddPlayer(context.Context, *AddPlayerRequest) (*GMDefaultResponse, error)
	DelPlayer(context.Context, *DelPlayerRequest) (*GMDefaultResponse, error)
	PlayerConn(Game_PlayerConnServer) error
	Start(context.Context, *GameStartRequest) (*GMDefaultResponse, error)
	Stop(context.Context, *GameStopRequest) (*GMDefaultResponse, error)
	Exit(context.Context, *GameExitRequest) (*GMDefaultResponse, error)
}

func RegisterGameServer(s *grpc.Server, srv GameServer) {
	s.RegisterService(&_Game_serviceDesc, srv)
}

func _Game_AddPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).AddPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/igm.Game/AddPlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).AddPlayer(ctx, req.(*AddPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_DelPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).DelPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/igm.Game/DelPlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).DelPlayer(ctx, req.(*DelPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_PlayerConn_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameServer).PlayerConn(&gamePlayerConnServer{stream})
}

type Game_PlayerConnServer interface {
	Send(*GameMessage) error
	Recv() (*PlayerMessage, error)
	grpc.ServerStream
}

type gamePlayerConnServer struct {
	grpc.ServerStream
}

func (x *gamePlayerConnServer) Send(m *GameMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gamePlayerConnServer) Recv() (*PlayerMessage, error) {
	m := new(PlayerMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Game_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/igm.Game/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).Start(ctx, req.(*GameStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/igm.Game/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).Stop(ctx, req.(*GameStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_Exit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameExitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).Exit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/igm.Game/Exit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).Exit(ctx, req.(*GameExitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Game_serviceDesc = grpc.ServiceDesc{
	ServiceName: "igm.Game",
	HandlerType: (*GameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPlayer",
			Handler:    _Game_AddPlayer_Handler,
		},
		{
			MethodName: "DelPlayer",
			Handler:    _Game_DelPlayer_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _Game_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Game_Stop_Handler,
		},
		{
			MethodName: "Exit",
			Handler:    _Game_Exit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PlayerConn",
			Handler:       _Game_PlayerConn_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "gm/gm.proto",
}

func init() { proto.RegisterFile("gm/gm.proto", fileDescriptor_910b291f729993e2) }

var fileDescriptor_910b291f729993e2 = []byte{
	// 716 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdb, 0x6e, 0xd3, 0x4c,
	0x10, 0xae, 0x63, 0x27, 0xad, 0x27, 0x7f, 0x7f, 0xd2, 0xa5, 0x94, 0xc8, 0x42, 0xa8, 0xb8, 0x02,
	0xf5, 0x2a, 0x45, 0x01, 0xa2, 0x52, 0x2a, 0xa0, 0xb4, 0x55, 0x55, 0x89, 0x0a, 0xe4, 0x52, 0x55,
	0xe2, 0x06, 0x19, 0x79, 0x6b, 0x59, 0x8d, 0x0f, 0x78, 0xd7, 0x40, 0x6e, 0x78, 0x11, 0xde, 0x82,
	0x87, 0xea, 0x73, 0xa0, 0xf5, 0xd8, 0xeb, 0x75, 0x42, 0x4a, 0x13, 0xae, 0xb2, 0x3b, 0x87, 0x6f,
	0xbe, 0x99, 0x9d, 0x19, 0x07, 0xda, 0x7e, 0xb8, 0xe5, 0x87, 0xbd, 0x24, 0x8d, 0x79, 0x4c, 0xf4,
	0xc0, 0x0f, 0xad, 0xdb, 0x8c, 0xbb, 0x3c, 0x63, 0x5b, 0xf8, 0x83, 0x1a, 0xfb, 0x01, 0x2c, 0x1f,
	0xb9, 0x21, 0x3d, 0x4b, 0x1c, 0xfa, 0x25, 0xa3, 0x8c, 0x93, 0x0e, 0xe8, 0x7e, 0xe0, 0x75, 0xb5,
	0x75, 0x6d, 0xd3, 0x74, 0xc4, 0xd1, 0x3e, 0x83, 0x15, 0x61, 0xb2, 0x9f, 0x52, 0x97, 0xd3, 0xd2,
	0xcc, 0x82, 0x25, 0xdf, 0x0d, 0xe9, 0x87, 0x51, 0x42, 0x73, 0x5b, 0xdd, 0x91, 0x77, 0x42, 0xc0,
	0x48, 0xe2, 0x94, 0x77, 0x1b, 0xb9, 0x3c, 0x3f, 0x97, 0xb0, 0x7a, 0x05, 0xfb, 0x03, 0x88, 0x0a,
	0xcb, 0x92, 0x38, 0x62, 0x94, 0x3c, 0x82, 0x16, 0xf2, 0xcb, 0x51, 0xdb, 0xfd, 0xff, 0x7b, 0x05,
	0xdd, 0xd3, 0xfc, 0xc7, 0x29, 0xb4, 0xb5, 0xf8, 0x8d, 0xb1, 0xf8, 0x13, 0xb1, 0x24, 0x23, 0xa3,
	0x62, 0x64, 0x3f, 0xc4, 0xb4, 0x0e, 0xe8, 0x90, 0x56, 0x69, 0x4d, 0x66, 0xbf, 0x01, 0xb7, 0x84,
	0xd9, 0xdb, 0x80, 0xf1, 0xe9, 0x46, 0x9f, 0xa0, 0x53, 0x19, 0xcd, 0x98, 0xc9, 0x06, 0x34, 0x05,
	0x73, 0xd6, 0x6d, 0xac, 0xeb, 0x9b, 0xed, 0xfe, 0x72, 0x2f, 0xf0, 0xc3, 0x9e, 0x40, 0x3b, 0x8e,
	0x2e, 0x62, 0x07, 0x75, 0xf6, 0x95, 0x06, 0x4b, 0xa5, 0x6c, 0x32, 0x3e, 0x59, 0x85, 0xa6, 0x40,
	0x2b, 0x4b, 0x81, 0x97, 0x5a, 0x8d, 0xf4, 0x29, 0x6f, 0x64, 0xd4, 0xdf, 0x28, 0x09, 0xbc, 0x6e,
	0x33, 0x17, 0x89, 0x23, 0x79, 0x0a, 0x8b, 0xc9, 0xd0, 0x1d, 0xd1, 0x94, 0x75, 0x5b, 0x39, 0x3b,
	0xab, 0xc6, 0xae, 0xf7, 0x1e, 0x95, 0x87, 0x11, 0x4f, 0x47, 0x4e, 0x69, 0x6a, 0xed, 0xc0, 0x7f,
	0xaa, 0x42, 0xe0, 0x5e, 0xd2, 0x51, 0xc9, 0xf7, 0x92, 0x8e, 0x04, 0xdf, 0xaf, 0xee, 0x30, 0x43,
	0xbe, 0xa6, 0x83, 0x97, 0x9d, 0xc6, 0xb6, 0x66, 0x0f, 0xb0, 0x92, 0xa7, 0xdc, 0x4d, 0xa7, 0xd7,
	0xbb, 0x64, 0x8a, 0xde, 0xe2, 0x68, 0x3f, 0xc3, 0x67, 0x3a, 0xe5, 0x71, 0x32, 0x8b, 0xdb, 0x0b,
	0x58, 0x39, 0x3a, 0x39, 0xa0, 0x17, 0x6e, 0x36, 0x9c, 0xf9, 0xe5, 0xca, 0x98, 0x87, 0xdf, 0x83,
	0x99, 0xa8, 0x0e, 0xa0, 0xb3, 0xe7, 0x79, 0x58, 0xa1, 0x19, 0xfd, 0x0e, 0xe8, 0x70, 0x76, 0xbf,
	0x73, 0x58, 0x51, 0xe2, 0xcd, 0x37, 0x67, 0x7b, 0x9e, 0x97, 0x16, 0x98, 0xf2, 0x6e, 0xff, 0xd4,
	0xa0, 0x2d, 0x0a, 0x70, 0x42, 0x19, 0x73, 0x7d, 0x4a, 0xba, 0xb0, 0x18, 0x32, 0x5f, 0x59, 0x09,
	0xe5, 0x95, 0xdc, 0x03, 0x73, 0x14, 0x67, 0xe9, 0xbe, 0x9b, 0x7a, 0xd8, 0xe7, 0xba, 0x53, 0x09,
	0x84, 0x76, 0xe8, 0x32, 0x8e, 0x5a, 0x1d, 0xb5, 0x52, 0x40, 0xd6, 0xa0, 0x25, 0x2e, 0xc7, 0x5e,
	0xde, 0xab, 0xa6, 0x53, 0xdc, 0xc8, 0x7d, 0x80, 0x34, 0xce, 0x22, 0xef, 0xdd, 0xb7, 0x88, 0xa6,
	0x79, 0xd3, 0x9a, 0x8e, 0x22, 0xb1, 0xcf, 0x61, 0x19, 0x73, 0xfe, 0x3b, 0x3d, 0x0b, 0x96, 0x92,
	0x8c, 0xab, 0xec, 0xe4, 0xbd, 0xac, 0xa7, 0x2e, 0xeb, 0xd9, 0xff, 0x65, 0x40, 0xe3, 0xe8, 0x84,
	0xbc, 0x02, 0xa8, 0xf6, 0x17, 0x59, 0x93, 0x83, 0x51, 0xdb, 0x93, 0xd6, 0xdd, 0x09, 0x39, 0x3e,
	0x80, 0xbd, 0x40, 0x5e, 0x22, 0x00, 0x2e, 0x20, 0x05, 0xa0, 0xb6, 0x91, 0xac, 0x42, 0x3e, 0xde,
	0xa4, 0xf6, 0x02, 0x79, 0x8e, 0x2b, 0x41, 0x2c, 0x1d, 0xb2, 0x2a, 0xbd, 0x95, 0x45, 0x65, 0xdd,
	0x19, 0x93, 0x4a, 0xd7, 0x5d, 0x30, 0xe5, 0x94, 0x91, 0xca, 0x4a, 0x9d, 0xba, 0x6b, 0x02, 0xef,
	0x60, 0x60, 0x31, 0x6b, 0x4a, 0x60, 0x65, 0xf4, 0xae, 0xf1, 0x7d, 0x8d, 0xdf, 0x1b, 0xd9, 0x90,
	0x45, 0xf4, 0xf1, 0x81, 0x28, 0x10, 0x26, 0xfa, 0xb6, 0x42, 0x90, 0xa3, 0x50, 0x20, 0x8c, 0x8f,
	0xc6, 0x35, 0x1c, 0x06, 0xd0, 0xc2, 0x6f, 0x1e, 0x21, 0x92, 0xfd, 0x59, 0x72, 0xe3, 0xbc, 0xc5,
	0xbc, 0x2b, 0x79, 0x2b, 0xe3, 0x3f, 0xdd, 0xb7, 0x7f, 0xd5, 0x00, 0x43, 0x58, 0x8b, 0xd2, 0xdf,
	0x30, 0xf9, 0x3f, 0x51, 0xd8, 0x05, 0xf3, 0x1f, 0x12, 0xdf, 0x06, 0x40, 0xd3, 0xfd, 0x38, 0x8a,
	0x8a, 0xe4, 0x6b, 0x33, 0x62, 0x75, 0x64, 0x5a, 0x85, 0xc4, 0x5e, 0xd8, 0xd4, 0x1e, 0x6b, 0x64,
	0x1b, 0x9a, 0x73, 0x36, 0xcb, 0x00, 0x8c, 0xb9, 0x1a, 0x65, 0x00, 0xc6, 0x3c, 0x85, 0x7e, 0x63,
	0x7e, 0x5c, 0x74, 0x93, 0x60, 0x2b, 0xf0, 0xc3, 0xcf, 0xad, 0xfc, 0x2f, 0xce, 0x93, 0xdf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x70, 0x92, 0x2d, 0x59, 0x0b, 0x09, 0x00, 0x00,
}
